apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ../../base
  - https://raw.githubusercontent.com/kata-containers/kata-containers/3.21.0/tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
