package v1

import (
	v1 "k8s.io/api/core/v1"
	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExporterSpec defines the desired state of Exporter
// Scope is inferred from repo field: if repo is set, scope is repository; otherwise, scope is organization.
type ExporterSpec struct {
	// Owner specifies the GitHub organization or user
	// +kubebuilder:validation:Pattern=`^[^/]+$`
	Owner string `json:"owner"`
	// Repo specifies the GitHub repository name. If set, metrics are collected at repository level.
	// If not set, metrics are collected at organization level.
	// +kubebuilder:validation:Pattern=`^[^/]+$`
	// +optional
	Repo string `json:"repo,omitempty"`
	// Selects a key of a GitHub Token secret in the exporter's namespace
	TokenSecretKeyRef *v1.SecretKeySelector `json:"tokenSecretKeyRef,omitempty"`
	AppSecretRef      *v1.SecretEnvSource   `json:"appSecretRef,omitempty"`
	// +optional
	Template Template `json:"template,omitzero"`
}

// Template defines the pod template generated by exporter
type Template struct {
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
	// +kubebuilder:pruning:PreserveUnknownFields
	metaV1.ObjectMeta `json:"metadata,omitempty"`
}

// ExporterStatus defines the observed state of Exporter
type ExporterStatus struct{}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Exporter is the schema for the exporters API
type Exporter struct {
	metaV1.TypeMeta   `json:",inline"`
	metaV1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ExporterSpec   `json:"spec,omitempty"`
	Status ExporterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExporterList contains a list of Exporter
type ExporterList struct {
	metaV1.TypeMeta `json:",inline"`
	metaV1.ListMeta `json:"metadata,omitempty"`
	Items           []Exporter `json:"items"`
}
