apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cortex-bot

resources:
- ../../base
- destination_rule.yaml
- horizontal_pod_autoscaler.yaml
- job.yaml
- namespace.yaml
- network_policy.yaml
- peer_authentication.yaml
- service.yaml
- service_entry.yaml
- sidecar.yaml
- telemetry.yaml
- virtual_service.yaml
- minio
- redis

patches:
- path: patches/deployment.yaml
- path: patches/pod_disruption_budget.yaml

generators:
- secrets_from_vault.yaml
images:
- digest: sha256:04b76e1b128c3ed211d2c58d589679ef81f4c9fe07ba6ef32ebd655d089f9668
  name: ghcr.io/hippocampus-dev/hippocampus/chrome-devtools-protocol-server
  newName: ghcr.io/hippocampus-dev/hippocampus/chrome-devtools-protocol-server
- digest: sha256:d16ec56c8ab1dca16a0e041cd0c4f67c9b8041ae6e991390130974b160f8d4cd
  name: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
  newName: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
- digest: sha256:33f3725615057a568594c057adbeea059b298beb57e85c29646a6c5356cdff86
  name: ghcr.io/hippocampus-dev/hippocampus/playwright-mcp
  newName: ghcr.io/hippocampus-dev/hippocampus/playwright-mcp
- digest: sha256:1288bc1402ff434da6e98820b895becbcb9d8d8837fb095f339ef6150e219911
  name: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
- digest: sha256:ace3d71e6aba6a8462ebded479c9690fee3047a483cf76dd39c7c2e1b3c54a2b
  name: minio/mc
  newName: ghcr.io/hippocampus-dev/hippocampus/mirror/minio/mc
