apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster_role_binding.yaml
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:a46d124200dcda638dbdce360837bc9d5ede0cc0f2f8e627ae7c9124749c235d
  name: ghcr.io/hippocampus-dev/hippocampus/kube-crud-server
  newName: ghcr.io/hippocampus-dev/hippocampus/kube-crud-server
