apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster_role_binding.yaml
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:a2c75402bb222acfe3a9a73e5109e6cd32a8989e99400b5520dff977d4589604
  name: ghcr.io/hippocampus-dev/hippocampus/kube-crud-server
  newName: ghcr.io/hippocampus-dev/hippocampus/kube-crud-server
