apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:f1a85104b9773c7036ce94c5596dc082e905dff11f8b8af50087d1b3aaa6ad2e
  name: ghcr.io/hippocampus-dev/hippocampus/memory-bank
  newName: ghcr.io/hippocampus-dev/hippocampus/memory-bank
