apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:ffc42333e9986cc14977c819d9fb657179204e9155ae42768d637bbb482df483
  name: ghcr.io/hippocampus-dev/hippocampus/memory-bank
  newName: ghcr.io/hippocampus-dev/hippocampus/memory-bank
