apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:d101266dbf2824b638ba5152c4cdc1cbc275bbaea953d5cd9d9a8f3bef56829e
  name: ghcr.io/hippocampus-dev/hippocampus/memory-bank
  newName: ghcr.io/hippocampus-dev/hippocampus/memory-bank
