apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
- stateful_set.yaml

images:
- digest: sha256:437028727b616c04844aa4ce0b819d91f9724ea76c461f32f39a23e9336d9b75
  name: ghcr.io/hippocampus-dev/hippocampus/github-actions-runner-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/github-actions-runner-controller
