apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: loganomaly-events
spec:
  consumerGroup: loganomaly-events
  topics:
    - loganomaly-events
  bootstrapServers:
    - eventing-kafka-bootstrap.knative-eventing.svc.cluster.local:9092
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: loganomaly
