apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: cortex-api-

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: cortex-api
      variant: utilities

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"

resources:
  - ../../../../utilities/tls-intercept-proxy
  - authorization_policy.yaml
  - certificate.yaml
  - issuer.yaml
  - peer_authentication.yaml
  - sidecar.yaml
  - telemetry.yaml

patches:
  - path: patches/deployment.yaml
  - path: patches/pod_disruption_budget.yaml
  - path: patches/service.yaml
