apiVersion: kustomize.kaidotio.github.io/v1
kind: SecretsFromVault
metadata:
  name: dedicated-container-ingress-controller
spec:
  options:
    disableNameSuffixHash: true
  vaultSecrets:
    - path: /kv/data/dedicated-container-ingress-controller
      key: COOKIE_SECRET_KEY
