apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: api.spotify.com
spec:
  exportTo:
    - .
  hosts:
    - api.spotify.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS
