use std::io::Write;

pub fn export(
    directory: std::path::PathBuf,
) -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    let mut groups: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();

    for definition in inventory::iter::<ipc::Definition> {
        groups
            .entry(definition.file.to_string())
            .or_default()
            .push(definition.body.to_string());
    }

    for (file, bodies) in groups {
        let path = directory.join(&file);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let mut output = std::fs::File::create(path)?;
        output.write_all(br#"// This file is automatically @generated by ipc_build."#)?;
        output.write_all(b"\n")?;
        for body in bodies {
            output.write_all(body.as_bytes())?;
            output.write_all(b"\n")?;
        }
    }

    Ok(())
}
