apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: fuse-csi-driver.csi.kaidotio.github.io
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
    - Ephemeral
