resources:
- csi_driver.yaml
- daemon_set.yaml
- service_account.yaml
images:
- digest: sha256:abf43ebaeaf4b33037f763f82925b1730c294a5caaad8a7f43f12ac12a36b83c
  name: ghcr.io/hippocampus-dev/hippocampus/fuse-csi-driver
  newName: ghcr.io/hippocampus-dev/hippocampus/fuse-csi-driver
- digest: sha256:f032a0ca4c699eebe403988a0e217c3dfc82e2cee8b7d9d247a493e5a2425f24
  name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newName: ghcr.io/hippocampus-dev/hippocampus/mirror/registry.k8s.io/sig-storage/csi-node-driver-registrar
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
