apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:6c53cf9ce9c61c9632acf6a8cac012af83670c94639a1b99ba56439071087f58
  name: ghcr.io/hippocampus-dev/hippocampus/tauri-releases
  newName: ghcr.io/hippocampus-dev/hippocampus/tauri-releases
