apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:b44b4df2d5b2abcae84569579469cb32236bc1971a1e0f4fc3931cc338eb2ffc
  name: ghcr.io/hippocampus-dev/hippocampus/tauri-releases
  newName: ghcr.io/hippocampus-dev/hippocampus/tauri-releases
