{
 "title": "Node",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kube_pod_info, node)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 4, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(container_fs_usage_bytes * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(container_fs_inodes_total * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(container_file_descriptors * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) / sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))",
     "legendFormat": "CPU Requests %"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) / sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))",
     "legendFormat": "CPU Limits %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) / sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))",
     "legendFormat": "Memory Requests %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) / sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod))",
     "legendFormat": "Memory Limits %"
    }
   ]
  },
  { "title": "Summary per pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 16, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_created * 1000 * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(container_fs_usage_bytes * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(container_fs_inodes_total * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(container_file_descriptors * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "table",
   "gridPos": { "h": 16, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_created * 1000 * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_info{node=\"${node}\"}) by (node,namespace,pod)) by (namespace,pod) * on(namespace,pod) group_left(w) group(label_join(kube_pod_info, \"w\", \"/\", \"namespace\", \"pod\")) by (namespace,pod,w)"
    }
   ]
  }
 ]
}