{
 "title": "Namespace",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 4, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(container_fs_inodes_total{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(container_file_descriptors{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"${namespace}\",phase=\"Running\"} * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) / sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container))",
     "legendFormat": "CPU Requests %"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) / sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container))",
     "legendFormat": "CPU Limits %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) / sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container))",
     "legendFormat": "Memory Requests %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) / sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container))",
     "legendFormat": "Memory Limits %"
    }
   ]
  },
  { "title": "Summary per workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 16, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(container_fs_inodes_total{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(container_file_descriptors{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"${namespace}\",phase=\"Running\"} * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "table",
   "gridPos": { "h": 16, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\"}) by (workload,workload_type) * on(workload,workload_type) group_left(w) group(label_join(mixin_pod_workload, \"w\", \"/\", \"workload_type\", \"workload\")) by (workload,workload_type,w)"
    }
   ]
  }
 ]
}