{
 "title": "Pod",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 4, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${namespace}\",pod=\"${pod}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\",pod=\"${pod}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))"
    },
    {
     "expr": "sum(container_fs_inodes_total{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))"
    },
    {
     "expr": "sum(container_file_descriptors{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) / sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))",
     "legendFormat": "CPU Requests %"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) / sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))",
     "legendFormat": "CPU Limits %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) / sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))",
     "legendFormat": "Memory Requests %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) / sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container))",
     "legendFormat": "Memory Limits %"
    }
   ]
  },
  { "title": "Summary per container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 8, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_all_container_status_ready{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0) by (container)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0) by (container)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0) by (container)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",pod=\"${pod}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0) by (container)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${namespace}\",pod=\"${pod}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\",pod=\"${pod}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(container_fs_inodes_total{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(container_file_descriptors{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_all_container_status_ready{namespace=\"${namespace}\",pod=\"${pod}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container) > 0) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{namespace=\"${namespace}\",pod=\"${pod}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"${namespace}\",pod=\"${pod}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"${namespace}\",pod=\"${pod}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\",pod=\"${pod}\"}) by (namespace,pod,container)) by (container)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24 },
   "targets": [
    {
     "expr": "{grouping=~\"kubernetes.${namespace}.*\"} | pattern \"<raw>\" | json | kubernetes_pod_name = \"${pod}\" | line_format \"{{ $structural_message := index (fromJson $.raw) \\\"structural_message\\\" }}{{ if $structural_message }}{{ range $k, $v := $structural_message }}\\033[1;33m{{ $k }}\\033[0m={{ $v }}\\n{{ end }}{{ else }}{{ $.message }}{{ end }}\""
    }
   ]
  }
 ]
}