{
 "title": "Workload",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "workload_type",
    "query": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, workload_type)"
   },
   {
    "name": "workload",
    "query": "label_values(mixin_pod_workload{namespace=\"$namespace\",workload_type=\"$workload_type\"}, workload)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 4, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(container_fs_inodes_total{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(container_file_descriptors{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"${namespace}\",phase=\"Running\"} * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) / sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})",
     "legendFormat": "CPU Requests %"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) / sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})",
     "legendFormat": "CPU Limits %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) / sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})",
     "legendFormat": "Memory Requests %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) / sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left(workload,workload_type) group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"})",
     "legendFormat": "Memory Limits %"
    }
   ]
  },
  { "title": "Summary per pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 8, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_created{namespace=\"${namespace}\"} * 1000 * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"${namespace}\",phase=\"Running\"} * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"${namespace}\",container!=\"\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{namespace=\"${namespace}\",resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(container_fs_inodes_total{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(container_file_descriptors{namespace=\"${namespace}\"} * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"${namespace}\",phase=\"Running\"} * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_created{namespace=\"${namespace}\"} * 1000 * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"${namespace}\",phase=\"Running\"} * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{namespace=\"${namespace}\",container!=\"\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=\"${namespace}\"}[$__range]) * on(namespace,pod,container) group_left group(kube_pod_all_container_status_running{namespace=\"${namespace}\"}) by (namespace,pod,container) * on(namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=\"${namespace}\",workload_type=\"${workload_type}\",workload=\"${workload}\"}) by (pod)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24 },
   "targets": [
    {
     "expr": "{grouping=~\"kubernetes.${namespace}.${workload}\"} | pattern \"<raw>\" | json | line_format \"{{ $structural_message := index (fromJson $.raw) \\\"structural_message\\\" }}{{ if $structural_message }}{{ range $k, $v := $structural_message }}\\033[1;33m{{ $k }}\\033[0m={{ $v }}\\n{{ end }}{{ else }}{{ $.message }}{{ end }}\""
    }
   ]
  }
 ]
}