{
 "title": "Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running) / sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)",
     "legendFormat": "CPU Requests %"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running) / sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)",
     "legendFormat": "CPU Limits %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running) / sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)",
     "legendFormat": "Memory Requests %"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running) / sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)",
     "legendFormat": "Memory Limits %"
    }
   ]
  },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 4, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(container_fs_usage_bytes * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(container_fs_inodes_total * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(container_file_descriptors * on(namespace,pod,container) group_left kube_pod_all_container_status_running)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  { "title": "Summary per namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 16, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[$__range]) * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(container_fs_inodes_total * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(container_file_descriptors * on(namespace,pod,container) group_left kube_pod_all_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace)"
    }
   ]
  },
  { "title": "Summary per node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left count(sum(node_cpu_seconds_total * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node,cpu)) by (node))",
     "legendFormat": "CPU / Max"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left count(sum(node_cpu_seconds_total * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node,cpu)) by (node))",
     "legendFormat": "CPU Requests / Max"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left count(sum(node_cpu_seconds_total * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node,cpu)) by (node))",
     "legendFormat": "CPU Limits / Max"
    },
    {
     "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node))",
     "legendFormat": "Memory / Max"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left sum(node_memory_MemTotal_bytes * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node))",
     "legendFormat": "Memory Requests / Max"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left sum(node_memory_MemTotal_bytes * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node))",
     "legendFormat": "Memory Limits / Max"
    },
    {
     "expr": "1 - sum(sum(node_filesystem_avail_bytes{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node) / on(node) group_left sum(node_filesystem_size_bytes{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node))",
     "legendFormat": "Disk / Max"
    },
    {
     "expr": "1 - sum(sum(node_filesystem_files_free{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node) / on(node) group_left sum(node_filesystem_files{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node))",
     "legendFormat": "inode / Max"
    },
    {
     "expr": "sum(sum(node_nf_conntrack_entries * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node) / on(node) group_left sum(node_nf_conntrack_entries_limit * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node))",
     "legendFormat": "conntrack / Max"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Succeeded|Failed\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left kube_node_status_capacity{resource=\"pods\",unit=\"integer\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node))",
     "legendFormat": "Pods / Max"
    }
   ]
  },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 8, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_node_role) by (node,role)"
    },
    {
     "expr": "sum(kube_node_created * 1000) by (node)"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) by (node)"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left count(sum(node_cpu_seconds_total * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node,cpu)) by (node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left count(sum(node_cpu_seconds_total * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node,cpu)) by (node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"cpu\",unit=\"core\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left count(sum(node_cpu_seconds_total * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node,cpu)) by (node)) by (node)"
    },
    {
     "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_requests{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left sum(node_memory_MemTotal_bytes * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_all_container_resource_limits{resource=\"memory\",unit=\"byte\"} * on(namespace,pod,container) group_left kube_pod_all_container_status_running * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left sum(node_memory_MemTotal_bytes * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)) by (node)"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum((node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_avail_bytes{mountpoint=\"/\"}) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "1 - sum(sum(node_filesystem_avail_bytes{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node) / on(node) group_left sum(node_filesystem_size_bytes{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)) by (node)"
    },
    {
     "expr": "sum((node_filesystem_files{mountpoint=\"/\"} - node_filesystem_files_free{mountpoint=\"/\"}) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "1 - sum(sum(node_filesystem_files_free{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node) / on(node) group_left sum(node_filesystem_files{mountpoint=\"/\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)) by (node)"
    },
    {
     "expr": "sum(node_nf_conntrack_entries * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(sum(node_nf_conntrack_entries * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node) / on(node) group_left sum(node_nf_conntrack_entries_limit * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)) by (node)"
    },
    {
     "expr": "sum(node_network_arp_entries * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Succeeded|Failed\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Succeeded|Failed\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node) / on(node) group_left kube_node_status_capacity{resource=\"pods\",unit=\"integer\"} * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{id=\"/system.slice/kubelet.service\"}[$__range]), \"node\", \"$1\", \"instance\", \"(.*)\")) by (node)"
    },
    {
     "expr": "sum(label_replace(rate(container_memory_usage_bytes{id=\"/system.slice/kubelet.service\"}[$__range]), \"node\", \"$1\", \"instance\", \"(.*)\")) by (node)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24 },
   "targets": [
    {
     "expr": "sum(kube_node_role) by (node,role)"
    },
    {
     "expr": "sum(kube_node_created * 1000) by (node)"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) by (node)"
    },
    {
     "expr": "sum(rate(node_pressure_cpu_waiting_seconds_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_pressure_memory_waiting_seconds_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_pressure_memory_stalled_seconds_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_pressure_disk_waiting_seconds_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_pressure_disk_stalled_seconds_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_network_transmit_drop_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_softnet_dropped_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    },
    {
     "expr": "sum(rate(node_softnet_times_squeezed_total[$__range]) * on(namespace,pod) group_left(node) group(kube_pod_status_ready{condition=\"true\"} * on(namespace,pod) group_left(node) group(kube_pod_info{node!=\"\"}) by (node,namespace,pod)) by (namespace,pod,node)) by (node)"
    }
   ]
  }
 ]
}