apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: translator

resources:
- ../../base
- horizontal_pod_autoscaler.yaml
- job.yaml
- namespace.yaml
- network_policy.yaml
- peer_authentication.yaml
- service_entry.yaml
- sidecar.yaml
- telemetry.yaml
- virtual_service.yaml
- minio
- redis

patches:
- path: patches/deployment.yaml
- path: patches/pod_disruption_budget.yaml

generators:
- secrets_from_vault.yaml
images:
- digest: sha256:bf687ad26c08b5bfb6a7eb55e9fcb0f979fd5891db02e804848ed73c8d85545a
  name: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
  newName: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
- digest: sha256:a5d8e2b376a5210dec9f273ea721d162b4ed27df22f844ab80308862e2fa946d
  name: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
- digest: sha256:ace3d71e6aba6a8462ebded479c9690fee3047a483cf76dd39c7c2e1b3c54a2b
  name: minio/mc
  newName: ghcr.io/hippocampus-dev/hippocampus/mirror/minio/mc
