apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pod_disruption_budget.yaml

images:
- digest: sha256:b61a1219320104cd05ae3c52aaf0b84f66993f4e724244b86487e395e9eb9762
  name: ghcr.io/hippocampus-dev/hippocampus/cortex-bot
  newName: ghcr.io/hippocampus-dev/hippocampus/cortex-bot
