apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pod_disruption_budget.yaml

images:
- digest: sha256:1b11ed17c550d7029fc7d4b6bb120a888a3cf94ea3cbf19cd7b9e4c0283f35de
  name: ghcr.io/hippocampus-dev/hippocampus/cortex-bot
  newName: ghcr.io/hippocampus-dev/hippocampus/cortex-bot
