apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:a2e9cd936914f7a50e46872a92ef7a74d8d34e7c0484af56de418071c90f7ae8
  name: ghcr.io/hippocampus-dev/hippocampus/at-least-semaphore-pod-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/at-least-semaphore-pod-hook
