apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:b53bb08822de5ab2d79f3995e2e2832101b3e94e46d36315cd12c3059ee969a8
  name: ghcr.io/hippocampus-dev/hippocampus/at-least-semaphore-pod-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/at-least-semaphore-pod-hook
