apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:0bd69e4477fa5911e5980bc5552143d866082bbc1d3edb7bac22385a97612402
  name: ghcr.io/hippocampus-dev/hippocampus/at-least-semaphore-pod-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/at-least-semaphore-pod-hook
