apiVersion: v1
kind: Service
metadata:
  name: tls-intercept-proxy
spec:
  selector:
    app.kubernetes.io/component: tls-intercept-proxy
  ports:
    - name: tcp-proxy
      port: 3128
      protocol: TCP
      targetPort: tcp-proxy
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
