apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: |-
    sha256:943dc0b6d261a55a40a9c919b83a37ba1fb18efa29e239f1774eee4ebc23188c
    sha256:c835998819105d84d484918908df132807c78c05f3e0e649df0c0479c6780d98
  name: prom/pushgateway
  newName: ghcr.io/hippocampus-dev/hippocampus/mirror/prom/pushgateway
