apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alerthandler
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - messaging.knative.dev
    resources:
      - kafkachannels
    verbs:
      - get
      - patch
  - apiGroups:
      - internal.kafka.eventing.knative.dev
    resources:
      - consumergroups
    verbs:
      - get
      - patch
