apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml

configurations:
- kustomizeconfig.yaml

images:
- digest: sha256:73b58555f9ed7731fbb236330b3ad795d459892e1c120256611a536be2594861
  name: ghcr.io/hippocampus-dev/hippocampus/alerthandler
  newName: ghcr.io/hippocampus-dev/hippocampus/alerthandler
