apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
- validating_webhook_configuration.yaml
images:
- digest: sha256:e576ec9c5f7cc493430ca596941aef4665a79c56a0ea783b00530501dbbe03e3
  name: ghcr.io/hippocampus-dev/hippocampus/lifecycle-job-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/lifecycle-job-hook
