apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
- validating_webhook_configuration.yaml
images:
- digest: sha256:d3cfa03cbf1671929af18ba61efcece4eb3b1e28f001a6229211d263f7c1f7fd
  name: ghcr.io/hippocampus-dev/hippocampus/lifecycle-job-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/lifecycle-job-hook
