apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
- validating_webhook_configuration.yaml
images:
- digest: sha256:189ad3f66ed76e4e6bc3aa8e283d5db0951b9405e7d2785b789b87633f0190b8
  name: ghcr.io/hippocampus-dev/hippocampus/lifecycle-job-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/lifecycle-job-hook
