apiVersion: v1
kind: Service
metadata:
  name: gitlab-sso-bridge
spec:
  selector:
    app.kubernetes.io/component: gitlab-sso-bridge
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
