apiVersion: apps/v1
kind: Deployment
metadata:
  name: owasp-zap-controller
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels: &labels
      app.kubernetes.io/name: owasp-zap-controller
      app.kubernetes.io/component: ""
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      serviceAccountName: owasp-zap-controller
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: owasp-zap-controller
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsUser: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: ghcr.io/hippocampus-dev/hippocampus/owasp-zap-controller
          imagePullPolicy: IfNotPresent
          args:
            - --enable-leader-election
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-agent.otel.svc.cluster.local:4317
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: OTEL_TRACES_SAMPLER
              value: parentbased_traceidratio
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: OTEL_BSP_SCHEDULE_DELAY
              value: "5000"
            - name: OTEL_BSP_EXPORT_TIMEOUT
              value: "30000"
            - name: OTEL_BSP_MAX_QUEUE_SIZE
              value: "2048"
            - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
              value: "512"
            - name: OTEL_GO_X_EXEMPLAR
              value: "true"
            - name: OTEL_METRICS_EXEMPLAR_FILTER
              value: trace_based
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: probe
              containerPort: 8081
              protocol: TCP
            - name: server
              containerPort: 8082
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 3
            failureThreshold: 1
            timeoutSeconds: 5
          # owasp-zap-controller implements lameduck
          #lifecycle:
          #  preStop:
          #    exec:
          #      command: ["sleep", "3"]
