apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- service.yaml

images:
- digest: sha256:c24059047908119b5eb9350b83a4d1305e0a568005c59644ec8a2464c4d2c920
- digest: sha256:9a2e3ab86f138a3f584450b71e073b23fc3a46018ac28f88d3975706b2fa7dc5
  name: ghcr.io/hippocampus-dev/hippocampus/owasp-zap-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/owasp-zap-controller
