apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- service.yaml

images:
- digest: sha256:c24059047908119b5eb9350b83a4d1305e0a568005c59644ec8a2464c4d2c920
- digest: sha256:7e541c0d3c44bbdfc683783258d0b5a3a38fb5ac7600fc5d327ed2db814fdde4
  name: ghcr.io/hippocampus-dev/hippocampus/owasp-zap-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/owasp-zap-controller
