.DEFAULT_GOAL := plan

.PHONY: plan
plan:
	@dotenvx run -- terraform plan

.PHONY: apply
apply:
	@dotenvx run -- terraform apply

.PHONY: output
output:
	@dotenvx run -- terraform output

.PHONY: FORCE
FORCE:
