apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:578899d2e4dce237c5fd5aed1a2140cfcfdc0eeab7efbe132463273d2739069b
  name: ghcr.io/hippocampus-dev/hippocampus/cortex-api
  newName: ghcr.io/hippocampus-dev/hippocampus/cortex-api
