apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:12072a1cfb9f6ce8424f7826358df6ba720397ffa43289421fbf59831238d92a
- digest: sha256:4f41eec1624f5b1438f50572727ad6766f958b7d6001b3e3beb6153581d9acec
  name: ghcr.io/hippocampus-dev/hippocampus/cortex-api
  newName: ghcr.io/hippocampus-dev/hippocampus/cortex-api
