apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetragon-operator
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "2113"
        prometheus.io/path: "/metrics"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: tetragon-operator
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
