{
 "title": "Overview",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 24 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by (alertname)"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "table",
   "gridPos": { "h": 4, "w": 24 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active > 0) by (cluster_name)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 12, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[$__range])) by (destination_workload_namespace,destination_workload) * on(destination_workload_namespace,destination_workload) group_left(w) group(label_join(istio_requests_total, \"w\", \"/\", \"destination_workload_namespace\", \"destination_workload\")) by (destination_workload_namespace,destination_workload,w)"
    },
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"(500|502|503|504)\"}[$__range])) by (destination_workload_namespace,destination_workload) * on(destination_workload_namespace,destination_workload) group_left(w) group(label_join(istio_requests_total, \"w\", \"/\", \"destination_workload_namespace\", \"destination_workload\")) by (destination_workload_namespace,destination_workload,w)"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(istio_request_duration_milliseconds_bucket[$__range]))) by (destination_workload_namespace,destination_workload) * on(destination_workload_namespace,destination_workload) group_left(w) group(label_join(istio_requests_total, \"w\", \"/\", \"destination_workload_namespace\", \"destination_workload\")) by (destination_workload_namespace,destination_workload,w)"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(istio_request_duration_milliseconds_bucket[$__range]))) by (destination_workload_namespace,destination_workload) * on(destination_workload_namespace,destination_workload) group_left(w) group(label_join(istio_requests_total, \"w\", \"/\", \"destination_workload_namespace\", \"destination_workload\")) by (destination_workload_namespace,destination_workload,w)"
    }
   ]
  },
  {
   "title": "Blackhole Requests",
   "type": "table",
   "gridPos": { "h": 6, "w": 24 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"BlackHoleCluster\"}[$__range])) by (source_workload_namespace,source_workload) * on(source_workload_namespace,source_workload) group_left(w) group(label_join(istio_requests_total, \"w\", \"/\", \"source_workload_namespace\", \"source_workload\")) by (source_workload_namespace,source_workload,w)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_labels) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Preempted Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_events_total{reason=\"Preempted\"}[$__interval])) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "LOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(loc{type!=\"Total\"}) by (repository,type)",
     "legendFormat": "{{ repository }} {{ type }}"
    }
   ]
  }
 ]
}