{
 "title": "Lighthouse",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(lighthouse_score, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(lighthouse_score{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "form_factor",
    "query": "label_values(lighthouse_score{namespace=\"$namespace\",pod=\"$pod\"}, form_factor)"
   },
   {
    "name": "url",
    "query": "label_values(lighthouse_score{namespace=\"$namespace\",pod=\"$pod\",form_factor=~\"$form_factor\"}, url)"
   }
  ]
 },
 "panels": [
  { "title": "Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "lighthouse_score{namespace=~\"$namespace\",pod=~\"$pod\",form_factor=~\"$form_factor\",url=~\"$url\"}",
   "type": "table",
   "gridPos": { "h": 12, "w": 24 },
   "targets": [
    {
     "expr": "avg(lighthouse_score{namespace=~\"${namespace}\",pod=~\"${pod}\",form_factor=~\"${form_factor}\",url=~\"${url}\"}) by (namespace,pod,form_factor,url,category)"
    }
   ]
  },
  { "title": "Core Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Largest Contentful Paint",
   "type": "text",
   "gridPos": { "h": 8, "w": 24 },
   "options": {
    "content": "<div style=\"text-align: center\"><p><img src=\"https://web.dev/static/articles/lcp/image/good-lcp-values.svg?hl=ja\" style=\"height: 150px\" /></p><p>読み込みのパフォーマンスを測定するための指標です。<br>優れたユーザー エクスペリエンスを提供するためには、ページの読み込みが開始されてからの LCP を 2.5 秒以内にする必要があります。</p></div>"
   }
  },
  {
   "title": "Largest Contentful Paint / Server Response Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(lighthouse_audit{namespace=~\"${namespace}\",pod=~\"${pod}\",form_factor=~\"${form_factor}\",url=~\"${url}\",id=\"largest-contentful-paint\"}) by (form_factor,url)",
     "legendFormat": "LCP - {{ form_factor }}"
    },
    {
     "expr": "avg(lighthouse_audit{namespace=~\"${namespace}\",pod=~\"${pod}\",form_factor=~\"${form_factor}\",url=~\"${url}\",id=\"server-response-time\"}) by (form_factor,url)",
     "legendFormat": "SRT - {{ form_factor }}"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "text",
   "gridPos": { "h": 8, "w": 24 },
   "options": {
    "content": "<div style=\"text-align: center\"><p><img src=\"https://web.dev/static/articles/fid/image/good-fid-values-25.svg?hl=ja\" style=\"height: 150px\" /></p><p>インタラクティブ性を測定するための指標です。<br>優れたユーザー エクスペリエンスを提供するためには、ページの FID を 100 ミリ秒以下にする必要があります。</p></div>"
   }
  },
  {
   "title": "First Input Delay",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(lighthouse_audit{namespace=~\"${namespace}\",pod=~\"${pod}\",form_factor=~\"${form_factor}\",url=~\"${url}\",id=\"max-potential-fid\"}) by (form_factor,url)",
     "legendFormat": "FID - {{ form_factor }}"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "text",
   "gridPos": { "h": 8, "w": 24 },
   "options": {
    "content": "<div style=\"text-align: center\"><p><img src=\"https://web.dev/static/articles/cls/image/good-cls-values.svg?hl=ja\" style=\"height: 150px\" /></p><p>視覚的な安定性を測定するための指標です。<br>優れたユーザー エクスペリエンスを提供するためには、ページの CLS を 0.1 以下に維持する必要があります。</p></div>"
   }
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24 },
   "targets": [
    {
     "expr": "avg(lighthouse_audit{namespace=~\"${namespace}\",pod=~\"${pod}\",form_factor=~\"${form_factor}\",url=~\"${url}\",id=\"cumulative-layout-shift\"}) by (form_factor,url)",
     "legendFormat": "CLS - {{ form_factor }}"
    }
   ]
  }
 ]
}