apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:f9c2f5bc2e0f2a8f98c3c82425bb4037b113fc29ae3b78519d7c49087f35a84f
  name: ghcr.io/hippocampus-dev/hippocampus/litestream-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/litestream-hook
