apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:3427cd6b9b6ec42edf1eab8523a3552f67515ec2d5e6c07ae4849b8ad42f0bad
  name: ghcr.io/hippocampus-dev/hippocampus/litestream-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/litestream-hook
