apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pod_disruption_budget.yaml
- service.yaml
- stateful_set.yaml

images:
- name: alpine
  newName: ghcr.io/hippocampus-dev/hippocampus/mirror/alpine
  newTag: "3.21"
- digest: sha256:62ec36621d313d3435150ead6d8393b5b2be91c7d067d399d97449cb83c28cf1
  name: mattermost/mattermost-team-edition
  newName: ghcr.io/hippocampus-dev/hippocampus/mirror/mattermost/mattermost-team-edition
- name: nginx
  newName: ghcr.io/hippocampus-dev/hippocampus/mirror/nginx
  newTag: 1.27.3-bookworm
