apiVersion: v1
kind: Service
metadata:
  name: mattermost
spec:
  selector:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/component: ""
  ports:
    - name: http-proxy
      port: 8080
      protocol: TCP
      targetPort: http-proxy
    - name: http
      port: 8065
      protocol: TCP
      targetPort: http
