apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:eec2fcdc099d92d407b0f884299e18daabf94ba94ec18743dd4a6465bcc18b37
  name: ghcr.io/hippocampus-dev/hippocampus/device-flow-bridge
  newName: ghcr.io/hippocampus-dev/hippocampus/device-flow-bridge
