apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:aecd1d8f9c0581f28f8c3bc2bb5e2f7fa8daad7ae96bd68e20b7385e6e38f5e0
  name: ghcr.io/hippocampus-dev/hippocampus/device-flow-bridge
  newName: ghcr.io/hippocampus-dev/hippocampus/device-flow-bridge
