apiVersion: kustomize.kaidotio.github.io/v1
kind: SecretsFromVault
metadata:
  # The secretGenerator already holds the `mattermost` name
  name: mattermost-gitlab
spec:
  vaultSecrets:
    - path: /kv/data/mattermost
      key: GITLAB_SECRET
