apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mattermost
spec:
  gateways:
    - mattermost
  hosts:
    - mattermost.minikube.127.0.0.1.nip.io
    - mattermost.kaidotio.dev
  http:
    - route:
        - destination:
            host: mattermost
            port:
              number: 8065
      retries:
        attempts: 3
        retryOn: gateway-error,retriable-4xx,connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
