apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:ab631a3d75593f27d5f1c424adc55a7a927e4b156e08c770fde9420cf8ec3351
- digest: sha256:685e0dbd955a406377fc263281f08ac522a5af2200f26e65bb74377690cb2cae
  name: ghcr.io/hippocampus-dev/hippocampus/proxy-wasm
  newName: ghcr.io/hippocampus-dev/hippocampus/proxy-wasm
