apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:ab631a3d75593f27d5f1c424adc55a7a927e4b156e08c770fde9420cf8ec3351
- digest: sha256:b50e5a7ff01e6eddd164151ed81dbfa3235748ee13758b2e6d04b48d3c2eadfc
  name: ghcr.io/hippocampus-dev/hippocampus/proxy-wasm
  newName: ghcr.io/hippocampus-dev/hippocampus/proxy-wasm
