apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:d9f70c6f83df1190376429b5dec5abb7ec93211778aa07de343438e2d178271c
  name: ghcr.io/hippocampus-dev/hippocampus/url-shortener
  newName: ghcr.io/hippocampus-dev/hippocampus/url-shortener
