// This file is automatically @generated by ipc_build.
export type Settings = Setting[];
export interface Setting {
  current_value: Value;
  kind: Kind;
  handler_command: string;
}
export type Kind = "Switch" | "Input" | "Shortcut";
export type Value = boolean | string | any;
