// This file is automatically @generated by ipc_build.
export type TmuxWindows = TmuxWindow[];
export interface TmuxWindow {
  session_name: string;
  window_index: string;
  silent: boolean;
  title: string;
}
