apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hippocampus-dev-spotify-oauth-bridge

resources:
  - namespace.yaml
  - network_policy.yaml
  - waypoint.yaml
  - oauth-bridge
  - redis
