apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:17d31c2844927242bd173171ada3617759e9358c9d9d8724b242fba5b102f24b
  name: ghcr.io/hippocampus-dev/hippocampus/embedding-retrieval
  newName: ghcr.io/hippocampus-dev/hippocampus/embedding-retrieval
