apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:2a28f905c60135fc746fe29f56c4e25784788546d128f9fbef9598c677d47e1e
  name: ghcr.io/hippocampus-dev/hippocampus/embedding-retrieval
  newName: ghcr.io/hippocampus-dev/hippocampus/embedding-retrieval
