apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:3d39f5b5069f8248bd08d314a946f351e10410a637907e148df5a3ea20c2252c
  name: ghcr.io/hippocampus-dev/hippocampus/embedding-retrieval
  newName: ghcr.io/hippocampus-dev/hippocampus/embedding-retrieval
