apiVersion: apps/v1
kind: Deployment
metadata:
  name: loganomaly
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels: &labels
      app.kubernetes.io/name: loganomaly
      app.kubernetes.io/component: ""
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      serviceAccountName: loganomaly
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: loganomaly
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsUser: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: ghcr.io/hippocampus-dev/hippocampus/loganomaly
          imagePullPolicy: IfNotPresent
          args:
            - consumer
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            periodSeconds: 10
            failureThreshold: 3
