apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
images:
- digest: sha256:25f6bcfcf34c22e25e0fe9f7b6f96e7907a943be5246d9467994bf9bc42cfbc8
  name: ghcr.io/hippocampus-dev/hippocampus/loganomaly
  newName: ghcr.io/hippocampus-dev/hippocampus/loganomaly
