apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:3e19e816480bfb97a5d741ac5d5778ef79072c2196d7c74ac358aff91eece022
  name: ghcr.io/hippocampus-dev/hippocampus/http-kvs
  newName: ghcr.io/hippocampus-dev/hippocampus/http-kvs
