apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:17087c6f2fe00b5378c14df1226a98e2625eb92021ff2347dfee2a6745346b48
  name: ghcr.io/hippocampus-dev/hippocampus/http-kvs
  newName: ghcr.io/hippocampus-dev/hippocampus/http-kvs
