apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
images:
- digest: sha256:e1854caf83c3a1b15acf350fc7ecec107502ad6c316e7e43753f8c07e2761aff
  name: ghcr.io/hippocampus-dev/hippocampus/events-logger
  newName: ghcr.io/hippocampus-dev/hippocampus/events-logger
