apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
images:
- digest: sha256:593d5742374a5c02f5ccd8139def57a27e0eb84f22839b862df3379a650a40d2
  name: ghcr.io/hippocampus-dev/hippocampus/events-logger
  newName: ghcr.io/hippocampus-dev/hippocampus/events-logger
