apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:149f5daa0abd18120dd81480de0994b8cd2b611389eef2ca10e8c6a586de8390
  name: ghcr.io/hippocampus-dev/hippocampus/anonymous-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/anonymous-proxy
