apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:c72d235ae6e0cb7977d30778205a21bc70dbd0fbd10f4938f9c45ca5b6775360
  name: ghcr.io/hippocampus-dev/hippocampus/anonymous-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/anonymous-proxy
