apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
- stateful_set.yaml

configMapGenerator:
- files:
  - files/jupyterhub_config.py
  name: jupyterhub-hub
  options:
    immutable: true
images:
- digest: sha256:9f5e2ee3ea09d77c414c4e6875f07629a80dd357a3abad976dd8dfc2cf289962
- digest: sha256:cc1e62b68d91e5fbe347593901d0659073da370af1689223d8fbeb57af0674f5
  name: ghcr.io/hippocampus-dev/hippocampus/configurable-http-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/configurable-http-proxy
- digest: sha256:c2edeb133b3648db38efa613906898718fc4bc3acc3ea52c482edf854625af39
  name: ghcr.io/hippocampus-dev/hippocampus/jupyterhub
  newName: ghcr.io/hippocampus-dev/hippocampus/jupyterhub
