apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
- stateful_set.yaml

configMapGenerator:
- files:
  - files/jupyterhub_config.py
  name: jupyterhub-hub
  options:
    immutable: true
images:
- digest: sha256:178462dc3377c7aacc1b41ba3b4a17ac5070e19070b63878c2f1bfe2a0e1e0b0
  name: ghcr.io/hippocampus-dev/hippocampus/configurable-http-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/configurable-http-proxy
- digest: sha256:0082b9aac51601ee26c44a1ec3d073564d47c4a3729ec4381b9439c729407e4a
  name: ghcr.io/hippocampus-dev/hippocampus/jupyterhub
  newName: ghcr.io/hippocampus-dev/hippocampus/jupyterhub
