apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemon_set.yaml
images:
- digest: sha256:c99aa53abf02067b30a530c53ddaeae437706652cf837dfca3bb555142e33999
- digest: sha256:6d11e3601caf13453825d499532fc52c05f17108ef7ef6b8acbda32085bd5b7a
  name: ghcr.io/hippocampus-dev/hippocampus/fluentd-delayed-unlink
  newName: ghcr.io/hippocampus-dev/hippocampus/fluentd-delayed-unlink
