apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemon_set.yaml
images:
- digest: sha256:c99aa53abf02067b30a530c53ddaeae437706652cf837dfca3bb555142e33999
- digest: sha256:4c4e676b67026c4c6427cbca7ccc09f54388d06a75d6a877eba6597d870df030
  name: ghcr.io/hippocampus-dev/hippocampus/fluentd-delayed-unlink
  newName: ghcr.io/hippocampus-dev/hippocampus/fluentd-delayed-unlink
