apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemon_set.yaml
images:
- digest: sha256:c99aa53abf02067b30a530c53ddaeae437706652cf837dfca3bb555142e33999
- digest: sha256:99b245286ab5c5b449253ec551fc2645f1a37ff92ab14626d42dc3f20eed1ba6
  name: ghcr.io/hippocampus-dev/hippocampus/fluentd-delayed-unlink
  newName: ghcr.io/hippocampus-dev/hippocampus/fluentd-delayed-unlink
