apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:8932b61bb1f29ca841225d00a2d565406d462bf0c959e376a60d0c374cfe3e2e
  name: ghcr.io/hippocampus-dev/hippocampus/statefulset-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/statefulset-hook
