apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:ee137888cc9bdcd63ee1bba4634a518924cbcd89a0995772649215d57e33b389
  name: ghcr.io/hippocampus-dev/hippocampus/statefulset-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/statefulset-hook
