apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:99ae44012d07ecf1aaa85db71fb932ceda876695d31b69f088708df2438718eb
  name: ghcr.io/hippocampus-dev/hippocampus/statefulset-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/statefulset-hook
