apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: resource-field-hook
  annotations:
    cert-manager.io/inject-ca-from: resource-field-hook/resource-field-hook
