// Code generated by ogen, DO NOT EDIT.

package spotify

// AddItemsToPlaylistParams is parameters of add-items-to-playlist operation.
type AddItemsToPlaylistParams struct {
	PlaylistID string
	Position   OptInt    `json:",omitempty,omitzero"`
	Uris       OptString `json:",omitempty,omitzero"`
}

// AddToQueueParams is parameters of add-to-queue operation.
type AddToQueueParams struct {
	URI      string
	DeviceID OptString `json:",omitempty,omitzero"`
}

// AddTracksToPlaylistParams is parameters of add-tracks-to-playlist operation.
type AddTracksToPlaylistParams struct {
	PlaylistID string
	Position   OptInt    `json:",omitempty,omitzero"`
	Uris       OptString `json:",omitempty,omitzero"`
}

// ChangePlaylistDetailsParams is parameters of change-playlist-details operation.
type ChangePlaylistDetailsParams struct {
	PlaylistID string
}

// CheckCurrentUserFollowsParams is parameters of check-current-user-follows operation.
type CheckCurrentUserFollowsParams struct {
	Type CheckCurrentUserFollowsType
	Ids  string
}

// CheckIfUserFollowsPlaylistParams is parameters of check-if-user-follows-playlist operation.
type CheckIfUserFollowsPlaylistParams struct {
	PlaylistID string
	Ids        OptString `json:",omitempty,omitzero"`
}

// CheckLibraryContainsParams is parameters of check-library-contains operation.
type CheckLibraryContainsParams struct {
	Uris string
}

// CheckUsersSavedAlbumsParams is parameters of check-users-saved-albums operation.
type CheckUsersSavedAlbumsParams struct {
	Ids string
}

// CheckUsersSavedAudiobooksParams is parameters of check-users-saved-audiobooks operation.
type CheckUsersSavedAudiobooksParams struct {
	Ids string
}

// CheckUsersSavedEpisodesParams is parameters of check-users-saved-episodes operation.
type CheckUsersSavedEpisodesParams struct {
	Ids string
}

// CheckUsersSavedShowsParams is parameters of check-users-saved-shows operation.
type CheckUsersSavedShowsParams struct {
	Ids string
}

// CheckUsersSavedTracksParams is parameters of check-users-saved-tracks operation.
type CheckUsersSavedTracksParams struct {
	Ids string
}

// CreatePlaylistForUserParams is parameters of create-playlist-for-user operation.
type CreatePlaylistForUserParams struct {
	UserID string
}

// FollowArtistsUsersParams is parameters of follow-artists-users operation.
type FollowArtistsUsersParams struct {
	Type FollowArtistsUsersType
	Ids  string
}

// FollowPlaylistParams is parameters of follow-playlist operation.
type FollowPlaylistParams struct {
	PlaylistID string
}

// GetACategoriesPlaylistsParams is parameters of get-a-categories-playlists operation.
type GetACategoriesPlaylistsParams struct {
	CategoryID string
	Limit      OptInt `json:",omitempty,omitzero"`
	Offset     OptInt `json:",omitempty,omitzero"`
}

// GetACategoryParams is parameters of get-a-category operation.
type GetACategoryParams struct {
	CategoryID string
	Locale     OptString `json:",omitempty,omitzero"`
}

// GetAChapterParams is parameters of get-a-chapter operation.
type GetAChapterParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
}

// GetAListOfCurrentUsersPlaylistsParams is parameters of get-a-list-of-current-users-playlists operation.
type GetAListOfCurrentUsersPlaylistsParams struct {
	Limit  OptInt `json:",omitempty,omitzero"`
	Offset OptInt `json:",omitempty,omitzero"`
}

// GetAShowParams is parameters of get-a-show operation.
type GetAShowParams struct {
	Market OptString `json:",omitempty,omitzero"`
	ID     string
}

// GetAShowsEpisodesParams is parameters of get-a-shows-episodes operation.
type GetAShowsEpisodesParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// GetAnAlbumParams is parameters of get-an-album operation.
type GetAnAlbumParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
}

// GetAnAlbumsTracksParams is parameters of get-an-albums-tracks operation.
type GetAnAlbumsTracksParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// GetAnArtistParams is parameters of get-an-artist operation.
type GetAnArtistParams struct {
	ID string
}

// GetAnArtistsAlbumsParams is parameters of get-an-artists-albums operation.
type GetAnArtistsAlbumsParams struct {
	ID            string
	IncludeGroups OptString `json:",omitempty,omitzero"`
	Market        OptString `json:",omitempty,omitzero"`
	Limit         OptInt    `json:",omitempty,omitzero"`
	Offset        OptInt    `json:",omitempty,omitzero"`
}

// GetAnArtistsRelatedArtistsParams is parameters of get-an-artists-related-artists operation.
type GetAnArtistsRelatedArtistsParams struct {
	ID string
}

// GetAnArtistsTopTracksParams is parameters of get-an-artists-top-tracks operation.
type GetAnArtistsTopTracksParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
}

// GetAnAudiobookParams is parameters of get-an-audiobook operation.
type GetAnAudiobookParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
}

// GetAnEpisodeParams is parameters of get-an-episode operation.
type GetAnEpisodeParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
}

// GetAudioAnalysisParams is parameters of get-audio-analysis operation.
type GetAudioAnalysisParams struct {
	ID string
}

// GetAudioFeaturesParams is parameters of get-audio-features operation.
type GetAudioFeaturesParams struct {
	ID string
}

// GetAudiobookChaptersParams is parameters of get-audiobook-chapters operation.
type GetAudiobookChaptersParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// GetCategoriesParams is parameters of get-categories operation.
type GetCategoriesParams struct {
	Locale OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// GetFeaturedPlaylistsParams is parameters of get-featured-playlists operation.
type GetFeaturedPlaylistsParams struct {
	Locale OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// GetFollowedParams is parameters of get-followed operation.
type GetFollowedParams struct {
	Type  GetFollowedType
	After OptString `json:",omitempty,omitzero"`
	Limit OptInt    `json:",omitempty,omitzero"`
}

// GetInformationAboutTheUsersCurrentPlaybackParams is parameters of get-information-about-the-users-current-playback operation.
type GetInformationAboutTheUsersCurrentPlaybackParams struct {
	Market          OptString `json:",omitempty,omitzero"`
	AdditionalTypes OptString `json:",omitempty,omitzero"`
}

// GetListUsersPlaylistsParams is parameters of get-list-users-playlists operation.
type GetListUsersPlaylistsParams struct {
	UserID string
	Limit  OptInt `json:",omitempty,omitzero"`
	Offset OptInt `json:",omitempty,omitzero"`
}

// GetMultipleAlbumsParams is parameters of get-multiple-albums operation.
type GetMultipleAlbumsParams struct {
	Ids    string
	Market OptString `json:",omitempty,omitzero"`
}

// GetMultipleArtistsParams is parameters of get-multiple-artists operation.
type GetMultipleArtistsParams struct {
	Ids string
}

// GetMultipleAudiobooksParams is parameters of get-multiple-audiobooks operation.
type GetMultipleAudiobooksParams struct {
	Ids    string
	Market OptString `json:",omitempty,omitzero"`
}

// GetMultipleEpisodesParams is parameters of get-multiple-episodes operation.
type GetMultipleEpisodesParams struct {
	Ids    string
	Market OptString `json:",omitempty,omitzero"`
}

// GetMultipleShowsParams is parameters of get-multiple-shows operation.
type GetMultipleShowsParams struct {
	Market OptString `json:",omitempty,omitzero"`
	Ids    string
}

// GetNewReleasesParams is parameters of get-new-releases operation.
type GetNewReleasesParams struct {
	Limit  OptInt `json:",omitempty,omitzero"`
	Offset OptInt `json:",omitempty,omitzero"`
}

// GetPlaylistParams is parameters of get-playlist operation.
type GetPlaylistParams struct {
	PlaylistID      string
	Market          OptString `json:",omitempty,omitzero"`
	Fields          OptString `json:",omitempty,omitzero"`
	AdditionalTypes OptString `json:",omitempty,omitzero"`
}

// GetPlaylistCoverParams is parameters of get-playlist-cover operation.
type GetPlaylistCoverParams struct {
	PlaylistID string
}

// GetPlaylistsItemsParams is parameters of get-playlists-items operation.
type GetPlaylistsItemsParams struct {
	PlaylistID      string
	Market          OptString `json:",omitempty,omitzero"`
	Fields          OptString `json:",omitempty,omitzero"`
	Limit           OptInt    `json:",omitempty,omitzero"`
	Offset          OptInt    `json:",omitempty,omitzero"`
	AdditionalTypes OptString `json:",omitempty,omitzero"`
}

// GetPlaylistsTracksParams is parameters of get-playlists-tracks operation.
type GetPlaylistsTracksParams struct {
	PlaylistID      string
	Market          OptString `json:",omitempty,omitzero"`
	Fields          OptString `json:",omitempty,omitzero"`
	Limit           OptInt    `json:",omitempty,omitzero"`
	Offset          OptInt    `json:",omitempty,omitzero"`
	AdditionalTypes OptString `json:",omitempty,omitzero"`
}

// GetRecentlyPlayedParams is parameters of get-recently-played operation.
type GetRecentlyPlayedParams struct {
	Limit  OptInt `json:",omitempty,omitzero"`
	After  OptInt `json:",omitempty,omitzero"`
	Before OptInt `json:",omitempty,omitzero"`
}

// GetRecommendationsParams is parameters of get-recommendations operation.
type GetRecommendationsParams struct {
	Limit                  OptInt    `json:",omitempty,omitzero"`
	Market                 OptString `json:",omitempty,omitzero"`
	SeedArtists            string
	SeedGenres             string
	SeedTracks             string
	MinAcousticness        OptFloat64 `json:",omitempty,omitzero"`
	MaxAcousticness        OptFloat64 `json:",omitempty,omitzero"`
	TargetAcousticness     OptFloat64 `json:",omitempty,omitzero"`
	MinDanceability        OptFloat64 `json:",omitempty,omitzero"`
	MaxDanceability        OptFloat64 `json:",omitempty,omitzero"`
	TargetDanceability     OptFloat64 `json:",omitempty,omitzero"`
	MinDurationMs          OptInt     `json:",omitempty,omitzero"`
	MaxDurationMs          OptInt     `json:",omitempty,omitzero"`
	TargetDurationMs       OptInt     `json:",omitempty,omitzero"`
	MinEnergy              OptFloat64 `json:",omitempty,omitzero"`
	MaxEnergy              OptFloat64 `json:",omitempty,omitzero"`
	TargetEnergy           OptFloat64 `json:",omitempty,omitzero"`
	MinInstrumentalness    OptFloat64 `json:",omitempty,omitzero"`
	MaxInstrumentalness    OptFloat64 `json:",omitempty,omitzero"`
	TargetInstrumentalness OptFloat64 `json:",omitempty,omitzero"`
	MinKey                 OptInt     `json:",omitempty,omitzero"`
	MaxKey                 OptInt     `json:",omitempty,omitzero"`
	TargetKey              OptInt     `json:",omitempty,omitzero"`
	MinLiveness            OptFloat64 `json:",omitempty,omitzero"`
	MaxLiveness            OptFloat64 `json:",omitempty,omitzero"`
	TargetLiveness         OptFloat64 `json:",omitempty,omitzero"`
	MinLoudness            OptFloat64 `json:",omitempty,omitzero"`
	MaxLoudness            OptFloat64 `json:",omitempty,omitzero"`
	TargetLoudness         OptFloat64 `json:",omitempty,omitzero"`
	MinMode                OptInt     `json:",omitempty,omitzero"`
	MaxMode                OptInt     `json:",omitempty,omitzero"`
	TargetMode             OptInt     `json:",omitempty,omitzero"`
	MinPopularity          OptInt     `json:",omitempty,omitzero"`
	MaxPopularity          OptInt     `json:",omitempty,omitzero"`
	TargetPopularity       OptInt     `json:",omitempty,omitzero"`
	MinSpeechiness         OptFloat64 `json:",omitempty,omitzero"`
	MaxSpeechiness         OptFloat64 `json:",omitempty,omitzero"`
	TargetSpeechiness      OptFloat64 `json:",omitempty,omitzero"`
	MinTempo               OptFloat64 `json:",omitempty,omitzero"`
	MaxTempo               OptFloat64 `json:",omitempty,omitzero"`
	TargetTempo            OptFloat64 `json:",omitempty,omitzero"`
	MinTimeSignature       OptInt     `json:",omitempty,omitzero"`
	MaxTimeSignature       OptInt     `json:",omitempty,omitzero"`
	TargetTimeSignature    OptInt     `json:",omitempty,omitzero"`
	MinValence             OptFloat64 `json:",omitempty,omitzero"`
	MaxValence             OptFloat64 `json:",omitempty,omitzero"`
	TargetValence          OptFloat64 `json:",omitempty,omitzero"`
}

// GetSeveralAudioFeaturesParams is parameters of get-several-audio-features operation.
type GetSeveralAudioFeaturesParams struct {
	Ids string
}

// GetSeveralChaptersParams is parameters of get-several-chapters operation.
type GetSeveralChaptersParams struct {
	Ids    string
	Market OptString `json:",omitempty,omitzero"`
}

// GetSeveralTracksParams is parameters of get-several-tracks operation.
type GetSeveralTracksParams struct {
	Market OptString `json:",omitempty,omitzero"`
	Ids    string
}

// GetTheUsersCurrentlyPlayingTrackParams is parameters of get-the-users-currently-playing-track operation.
type GetTheUsersCurrentlyPlayingTrackParams struct {
	Market          OptString `json:",omitempty,omitzero"`
	AdditionalTypes OptString `json:",omitempty,omitzero"`
}

// GetTrackParams is parameters of get-track operation.
type GetTrackParams struct {
	ID     string
	Market OptString `json:",omitempty,omitzero"`
}

// GetUsersProfileParams is parameters of get-users-profile operation.
type GetUsersProfileParams struct {
	UserID string
}

// GetUsersSavedAlbumsParams is parameters of get-users-saved-albums operation.
type GetUsersSavedAlbumsParams struct {
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
	Market OptString `json:",omitempty,omitzero"`
}

// GetUsersSavedAudiobooksParams is parameters of get-users-saved-audiobooks operation.
type GetUsersSavedAudiobooksParams struct {
	Limit  OptInt `json:",omitempty,omitzero"`
	Offset OptInt `json:",omitempty,omitzero"`
}

// GetUsersSavedEpisodesParams is parameters of get-users-saved-episodes operation.
type GetUsersSavedEpisodesParams struct {
	Market OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// GetUsersSavedShowsParams is parameters of get-users-saved-shows operation.
type GetUsersSavedShowsParams struct {
	Limit  OptInt `json:",omitempty,omitzero"`
	Offset OptInt `json:",omitempty,omitzero"`
}

// GetUsersSavedTracksParams is parameters of get-users-saved-tracks operation.
type GetUsersSavedTracksParams struct {
	Market OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// GetUsersTopArtistsAndTracksParams is parameters of get-users-top-artists-and-tracks operation.
type GetUsersTopArtistsAndTracksParams struct {
	Type      GetUsersTopArtistsAndTracksType
	TimeRange OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
	Offset    OptInt    `json:",omitempty,omitzero"`
}

// PauseAUsersPlaybackParams is parameters of pause-a-users-playback operation.
type PauseAUsersPlaybackParams struct {
	DeviceID OptString `json:",omitempty,omitzero"`
}

// RemoveAlbumsUserParams is parameters of remove-albums-user operation.
type RemoveAlbumsUserParams struct {
	Ids string
}

// RemoveAudiobooksUserParams is parameters of remove-audiobooks-user operation.
type RemoveAudiobooksUserParams struct {
	Ids string
}

// RemoveEpisodesUserParams is parameters of remove-episodes-user operation.
type RemoveEpisodesUserParams struct {
	Ids string
}

// RemoveItemsPlaylistParams is parameters of remove-items-playlist operation.
type RemoveItemsPlaylistParams struct {
	PlaylistID string
}

// RemoveLibraryItemsParams is parameters of remove-library-items operation.
type RemoveLibraryItemsParams struct {
	Uris string
}

// RemoveShowsUserParams is parameters of remove-shows-user operation.
type RemoveShowsUserParams struct {
	Ids    string
	Market OptString `json:",omitempty,omitzero"`
}

// RemoveTracksPlaylistParams is parameters of remove-tracks-playlist operation.
type RemoveTracksPlaylistParams struct {
	PlaylistID string
}

// RemoveTracksUserParams is parameters of remove-tracks-user operation.
type RemoveTracksUserParams struct {
	Ids string
}

// ReorderOrReplacePlaylistsItemsParams is parameters of reorder-or-replace-playlists-items operation.
type ReorderOrReplacePlaylistsItemsParams struct {
	PlaylistID string
	Uris       OptString `json:",omitempty,omitzero"`
}

// ReorderOrReplacePlaylistsTracksParams is parameters of reorder-or-replace-playlists-tracks operation.
type ReorderOrReplacePlaylistsTracksParams struct {
	PlaylistID string
	Uris       OptString `json:",omitempty,omitzero"`
}

// SaveAlbumsUserParams is parameters of save-albums-user operation.
type SaveAlbumsUserParams struct {
	Ids string
}

// SaveAudiobooksUserParams is parameters of save-audiobooks-user operation.
type SaveAudiobooksUserParams struct {
	Ids string
}

// SaveEpisodesUserParams is parameters of save-episodes-user operation.
type SaveEpisodesUserParams struct {
	Ids string
}

// SaveLibraryItemsParams is parameters of save-library-items operation.
type SaveLibraryItemsParams struct {
	Uris string
}

// SaveShowsUserParams is parameters of save-shows-user operation.
type SaveShowsUserParams struct {
	Ids string
}

// SearchParams is parameters of search operation.
type SearchParams struct {
	Q               string
	Type            []SearchTypeItem         `json:",omitempty"`
	Market          OptString                `json:",omitempty,omitzero"`
	Limit           OptInt                   `json:",omitempty,omitzero"`
	Offset          OptInt                   `json:",omitempty,omitzero"`
	IncludeExternal OptSearchIncludeExternal `json:",omitempty,omitzero"`
}

// SeekToPositionInCurrentlyPlayingTrackParams is parameters of seek-to-position-in-currently-playing-track operation.
type SeekToPositionInCurrentlyPlayingTrackParams struct {
	PositionMs int
	DeviceID   OptString `json:",omitempty,omitzero"`
}

// SetRepeatModeOnUsersPlaybackParams is parameters of set-repeat-mode-on-users-playback operation.
type SetRepeatModeOnUsersPlaybackParams struct {
	State    string
	DeviceID OptString `json:",omitempty,omitzero"`
}

// SetVolumeForUsersPlaybackParams is parameters of set-volume-for-users-playback operation.
type SetVolumeForUsersPlaybackParams struct {
	VolumePercent int
	DeviceID      OptString `json:",omitempty,omitzero"`
}

// SkipUsersPlaybackToNextTrackParams is parameters of skip-users-playback-to-next-track operation.
type SkipUsersPlaybackToNextTrackParams struct {
	DeviceID OptString `json:",omitempty,omitzero"`
}

// SkipUsersPlaybackToPreviousTrackParams is parameters of skip-users-playback-to-previous-track operation.
type SkipUsersPlaybackToPreviousTrackParams struct {
	DeviceID OptString `json:",omitempty,omitzero"`
}

// StartAUsersPlaybackParams is parameters of start-a-users-playback operation.
type StartAUsersPlaybackParams struct {
	DeviceID OptString `json:",omitempty,omitzero"`
}

// ToggleShuffleForUsersPlaybackParams is parameters of toggle-shuffle-for-users-playback operation.
type ToggleShuffleForUsersPlaybackParams struct {
	State    bool
	DeviceID OptString `json:",omitempty,omitzero"`
}

// UnfollowArtistsUsersParams is parameters of unfollow-artists-users operation.
type UnfollowArtistsUsersParams struct {
	Type UnfollowArtistsUsersType
	Ids  string
}

// UnfollowPlaylistParams is parameters of unfollow-playlist operation.
type UnfollowPlaylistParams struct {
	PlaylistID string
}

// UploadCustomPlaylistCoverParams is parameters of upload-custom-playlist-cover operation.
type UploadCustomPlaylistCoverParams struct {
	PlaylistID string
}
