// Code generated by ogen, DO NOT EDIT.
package spotify

type AddItemsToPlaylistRes interface {
	addItemsToPlaylistRes()
}

type AddToQueueRes interface {
	addToQueueRes()
}

type AddTracksToPlaylistRes interface {
	addTracksToPlaylistRes()
}

type ChangePlaylistDetailsRes interface {
	changePlaylistDetailsRes()
}

type CheckCurrentUserFollowsRes interface {
	checkCurrentUserFollowsRes()
}

type CheckIfUserFollowsPlaylistRes interface {
	checkIfUserFollowsPlaylistRes()
}

type CheckLibraryContainsRes interface {
	checkLibraryContainsRes()
}

type CheckUsersSavedAlbumsRes interface {
	checkUsersSavedAlbumsRes()
}

type CheckUsersSavedAudiobooksRes interface {
	checkUsersSavedAudiobooksRes()
}

type CheckUsersSavedEpisodesRes interface {
	checkUsersSavedEpisodesRes()
}

type CheckUsersSavedShowsRes interface {
	checkUsersSavedShowsRes()
}

type CheckUsersSavedTracksRes interface {
	checkUsersSavedTracksRes()
}

type CreatePlaylistForUserRes interface {
	createPlaylistForUserRes()
}

type CreatePlaylistRes interface {
	createPlaylistRes()
}

type FollowArtistsUsersRes interface {
	followArtistsUsersRes()
}

type FollowPlaylistRes interface {
	followPlaylistRes()
}

type GetACategoriesPlaylistsRes interface {
	getACategoriesPlaylistsRes()
}

type GetACategoryRes interface {
	getACategoryRes()
}

type GetAChapterRes interface {
	getAChapterRes()
}

type GetAListOfCurrentUsersPlaylistsRes interface {
	getAListOfCurrentUsersPlaylistsRes()
}

type GetAShowRes interface {
	getAShowRes()
}

type GetAShowsEpisodesRes interface {
	getAShowsEpisodesRes()
}

type GetAUsersAvailableDevicesRes interface {
	getAUsersAvailableDevicesRes()
}

type GetAnAlbumRes interface {
	getAnAlbumRes()
}

type GetAnAlbumsTracksRes interface {
	getAnAlbumsTracksRes()
}

type GetAnArtistRes interface {
	getAnArtistRes()
}

type GetAnArtistsAlbumsRes interface {
	getAnArtistsAlbumsRes()
}

type GetAnArtistsRelatedArtistsRes interface {
	getAnArtistsRelatedArtistsRes()
}

type GetAnArtistsTopTracksRes interface {
	getAnArtistsTopTracksRes()
}

type GetAnAudiobookRes interface {
	getAnAudiobookRes()
}

type GetAnEpisodeRes interface {
	getAnEpisodeRes()
}

type GetAudioAnalysisRes interface {
	getAudioAnalysisRes()
}

type GetAudioFeaturesRes interface {
	getAudioFeaturesRes()
}

type GetAudiobookChaptersRes interface {
	getAudiobookChaptersRes()
}

type GetAvailableMarketsRes interface {
	getAvailableMarketsRes()
}

type GetCategoriesRes interface {
	getCategoriesRes()
}

type GetCurrentUsersProfileRes interface {
	getCurrentUsersProfileRes()
}

type GetFeaturedPlaylistsRes interface {
	getFeaturedPlaylistsRes()
}

type GetFollowedRes interface {
	getFollowedRes()
}

type GetInformationAboutTheUsersCurrentPlaybackRes interface {
	getInformationAboutTheUsersCurrentPlaybackRes()
}

type GetListUsersPlaylistsRes interface {
	getListUsersPlaylistsRes()
}

type GetMultipleAlbumsRes interface {
	getMultipleAlbumsRes()
}

type GetMultipleArtistsRes interface {
	getMultipleArtistsRes()
}

type GetMultipleAudiobooksRes interface {
	getMultipleAudiobooksRes()
}

type GetMultipleEpisodesRes interface {
	getMultipleEpisodesRes()
}

type GetMultipleShowsRes interface {
	getMultipleShowsRes()
}

type GetNewReleasesRes interface {
	getNewReleasesRes()
}

type GetPlaylistCoverRes interface {
	getPlaylistCoverRes()
}

type GetPlaylistRes interface {
	getPlaylistRes()
}

type GetPlaylistsItemsRes interface {
	getPlaylistsItemsRes()
}

type GetPlaylistsTracksRes interface {
	getPlaylistsTracksRes()
}

type GetQueueRes interface {
	getQueueRes()
}

type GetRecentlyPlayedRes interface {
	getRecentlyPlayedRes()
}

type GetRecommendationGenresRes interface {
	getRecommendationGenresRes()
}

type GetRecommendationsRes interface {
	getRecommendationsRes()
}

type GetSeveralAudioFeaturesRes interface {
	getSeveralAudioFeaturesRes()
}

type GetSeveralChaptersRes interface {
	getSeveralChaptersRes()
}

type GetSeveralTracksRes interface {
	getSeveralTracksRes()
}

type GetTheUsersCurrentlyPlayingTrackRes interface {
	getTheUsersCurrentlyPlayingTrackRes()
}

type GetTrackRes interface {
	getTrackRes()
}

type GetUsersProfileRes interface {
	getUsersProfileRes()
}

type GetUsersSavedAlbumsRes interface {
	getUsersSavedAlbumsRes()
}

type GetUsersSavedAudiobooksRes interface {
	getUsersSavedAudiobooksRes()
}

type GetUsersSavedEpisodesRes interface {
	getUsersSavedEpisodesRes()
}

type GetUsersSavedShowsRes interface {
	getUsersSavedShowsRes()
}

type GetUsersSavedTracksRes interface {
	getUsersSavedTracksRes()
}

type GetUsersTopArtistsRes interface {
	getUsersTopArtistsRes()
}

type GetUsersTopTracksRes interface {
	getUsersTopTracksRes()
}

type PauseAUsersPlaybackRes interface {
	pauseAUsersPlaybackRes()
}

type RemoveAlbumsUserRes interface {
	removeAlbumsUserRes()
}

type RemoveAudiobooksUserRes interface {
	removeAudiobooksUserRes()
}

type RemoveEpisodesUserRes interface {
	removeEpisodesUserRes()
}

type RemoveItemsPlaylistRes interface {
	removeItemsPlaylistRes()
}

type RemoveLibraryItemsRes interface {
	removeLibraryItemsRes()
}

type RemoveShowsUserRes interface {
	removeShowsUserRes()
}

type RemoveTracksPlaylistRes interface {
	removeTracksPlaylistRes()
}

type RemoveTracksUserRes interface {
	removeTracksUserRes()
}

type ReorderOrReplacePlaylistsItemsRes interface {
	reorderOrReplacePlaylistsItemsRes()
}

type ReorderOrReplacePlaylistsTracksRes interface {
	reorderOrReplacePlaylistsTracksRes()
}

type SaveAlbumsUserRes interface {
	saveAlbumsUserRes()
}

type SaveAudiobooksUserRes interface {
	saveAudiobooksUserRes()
}

type SaveEpisodesUserRes interface {
	saveEpisodesUserRes()
}

type SaveLibraryItemsRes interface {
	saveLibraryItemsRes()
}

type SaveShowsUserRes interface {
	saveShowsUserRes()
}

type SaveTracksUserRes interface {
	saveTracksUserRes()
}

type SearchRes interface {
	searchRes()
}

type SeekToPositionInCurrentlyPlayingTrackRes interface {
	seekToPositionInCurrentlyPlayingTrackRes()
}

type SetRepeatModeOnUsersPlaybackRes interface {
	setRepeatModeOnUsersPlaybackRes()
}

type SetVolumeForUsersPlaybackRes interface {
	setVolumeForUsersPlaybackRes()
}

type SkipUsersPlaybackToNextTrackRes interface {
	skipUsersPlaybackToNextTrackRes()
}

type SkipUsersPlaybackToPreviousTrackRes interface {
	skipUsersPlaybackToPreviousTrackRes()
}

type StartAUsersPlaybackRes interface {
	startAUsersPlaybackRes()
}

type ToggleShuffleForUsersPlaybackRes interface {
	toggleShuffleForUsersPlaybackRes()
}

type TransferAUsersPlaybackRes interface {
	transferAUsersPlaybackRes()
}

type UnfollowArtistsUsersRes interface {
	unfollowArtistsUsersRes()
}

type UnfollowPlaylistRes interface {
	unfollowPlaylistRes()
}

type UploadCustomPlaylistCoverRes interface {
	uploadCustomPlaylistCoverRes()
}
