// Code generated by ogen, DO NOT EDIT.

package spotify

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// OAuth20 provides oauth_2_0 security value.
	// Spotify supports OAuth 2.0 for authenticating all API requests.
	OAuth20(ctx context.Context, operationName OperationName) (OAuth20, error)
}

// oauth2ScopesOAuth20 is a private map storing OAuth2 scopes per operation.
var oauth2ScopesOAuth20 = map[string][]string{
	AddItemsToPlaylistOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	AddToQueueOperation: []string{
		"user-modify-playback-state",
	},
	AddTracksToPlaylistOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	ChangePlaylistDetailsOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	CheckCurrentUserFollowsOperation: []string{
		"user-follow-read",
	},
	CheckIfUserFollowsPlaylistOperation: []string{},
	CheckLibraryContainsOperation: []string{
		"user-library-read",
		"user-follow-read",
		"playlist-read-private",
	},
	CheckUsersSavedAlbumsOperation: []string{
		"user-library-read",
	},
	CheckUsersSavedAudiobooksOperation: []string{
		"user-library-read",
	},
	CheckUsersSavedEpisodesOperation: []string{
		"user-library-read",
	},
	CheckUsersSavedShowsOperation: []string{
		"user-library-read",
	},
	CheckUsersSavedTracksOperation: []string{
		"user-library-read",
	},
	CreatePlaylistOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	CreatePlaylistForUserOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	FollowArtistsUsersOperation: []string{
		"user-follow-modify",
	},
	FollowPlaylistOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	GetACategoriesPlaylistsOperation: []string{},
	GetACategoryOperation:            []string{},
	GetAChapterOperation:             []string{},
	GetAListOfCurrentUsersPlaylistsOperation: []string{
		"playlist-read-private",
	},
	GetAShowOperation: []string{
		"user-read-playback-position",
	},
	GetAShowsEpisodesOperation: []string{
		"user-read-playback-position",
	},
	GetAUsersAvailableDevicesOperation: []string{
		"user-read-playback-state",
	},
	GetAnAlbumOperation:                 []string{},
	GetAnAlbumsTracksOperation:          []string{},
	GetAnArtistOperation:                []string{},
	GetAnArtistsAlbumsOperation:         []string{},
	GetAnArtistsRelatedArtistsOperation: []string{},
	GetAnArtistsTopTracksOperation:      []string{},
	GetAnAudiobookOperation:             []string{},
	GetAnEpisodeOperation: []string{
		"user-read-playback-position",
	},
	GetAudioAnalysisOperation:     []string{},
	GetAudioFeaturesOperation:     []string{},
	GetAudiobookChaptersOperation: []string{},
	GetAvailableMarketsOperation:  []string{},
	GetCategoriesOperation:        []string{},
	GetCurrentUsersProfileOperation: []string{
		"user-read-private",
		"user-read-email",
	},
	GetFeaturedPlaylistsOperation: []string{},
	GetFollowedOperation: []string{
		"user-follow-read",
	},
	GetInformationAboutTheUsersCurrentPlaybackOperation: []string{
		"user-read-playback-state",
	},
	GetListUsersPlaylistsOperation: []string{
		"playlist-read-private",
		"playlist-read-collaborative",
	},
	GetMultipleAlbumsOperation:     []string{},
	GetMultipleArtistsOperation:    []string{},
	GetMultipleAudiobooksOperation: []string{},
	GetMultipleEpisodesOperation: []string{
		"user-read-playback-position",
	},
	GetMultipleShowsOperation: []string{},
	GetNewReleasesOperation:   []string{},
	GetPlaylistOperation:      []string{},
	GetPlaylistCoverOperation: []string{},
	GetPlaylistsItemsOperation: []string{
		"playlist-read-private",
	},
	GetPlaylistsTracksOperation: []string{
		"playlist-read-private",
	},
	GetQueueOperation: []string{
		"user-read-currently-playing",
		"user-read-playback-state",
	},
	GetRecentlyPlayedOperation: []string{
		"user-read-recently-played",
	},
	GetRecommendationGenresOperation: []string{},
	GetRecommendationsOperation:      []string{},
	GetSeveralAudioFeaturesOperation: []string{},
	GetSeveralChaptersOperation:      []string{},
	GetSeveralTracksOperation:        []string{},
	GetTheUsersCurrentlyPlayingTrackOperation: []string{
		"user-read-currently-playing",
	},
	GetTrackOperation:        []string{},
	GetUsersProfileOperation: []string{},
	GetUsersSavedAlbumsOperation: []string{
		"user-library-read",
	},
	GetUsersSavedAudiobooksOperation: []string{
		"user-library-read",
	},
	GetUsersSavedEpisodesOperation: []string{
		"user-library-read",
		"user-read-playback-position",
	},
	GetUsersSavedShowsOperation: []string{
		"user-library-read",
	},
	GetUsersSavedTracksOperation: []string{
		"user-library-read",
	},
	GetUsersTopArtistsOperation: []string{
		"user-top-read",
	},
	GetUsersTopTracksOperation: []string{
		"user-top-read",
	},
	PauseAUsersPlaybackOperation: []string{
		"user-modify-playback-state",
	},
	RemoveAlbumsUserOperation: []string{
		"user-library-modify",
	},
	RemoveAudiobooksUserOperation: []string{
		"user-library-modify",
	},
	RemoveEpisodesUserOperation: []string{
		"user-library-modify",
	},
	RemoveItemsPlaylistOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	RemoveLibraryItemsOperation: []string{
		"user-library-modify",
		"user-follow-modify",
		"playlist-modify-public",
	},
	RemoveShowsUserOperation: []string{
		"user-library-modify",
	},
	RemoveTracksPlaylistOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	RemoveTracksUserOperation: []string{
		"user-library-modify",
	},
	ReorderOrReplacePlaylistsItemsOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	ReorderOrReplacePlaylistsTracksOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	SaveAlbumsUserOperation: []string{
		"user-library-modify",
	},
	SaveAudiobooksUserOperation: []string{
		"user-library-modify",
	},
	SaveEpisodesUserOperation: []string{
		"user-library-modify",
	},
	SaveLibraryItemsOperation: []string{
		"user-library-modify",
		"user-follow-modify",
		"playlist-modify-public",
	},
	SaveShowsUserOperation: []string{
		"user-library-modify",
	},
	SaveTracksUserOperation: []string{
		"user-library-modify",
	},
	SearchOperation: []string{},
	SeekToPositionInCurrentlyPlayingTrackOperation: []string{
		"user-modify-playback-state",
	},
	SetRepeatModeOnUsersPlaybackOperation: []string{
		"user-modify-playback-state",
	},
	SetVolumeForUsersPlaybackOperation: []string{
		"user-modify-playback-state",
	},
	SkipUsersPlaybackToNextTrackOperation: []string{
		"user-modify-playback-state",
	},
	SkipUsersPlaybackToPreviousTrackOperation: []string{
		"user-modify-playback-state",
	},
	StartAUsersPlaybackOperation: []string{
		"user-modify-playback-state",
	},
	ToggleShuffleForUsersPlaybackOperation: []string{
		"user-modify-playback-state",
	},
	TransferAUsersPlaybackOperation: []string{
		"user-modify-playback-state",
	},
	UnfollowArtistsUsersOperation: []string{
		"user-follow-modify",
	},
	UnfollowPlaylistOperation: []string{
		"playlist-modify-public",
		"playlist-modify-private",
	},
	UploadCustomPlaylistCoverOperation: []string{
		"ugc-image-upload",
		"playlist-modify-public",
		"playlist-modify-private",
	},
}

// GetOAuth2ScopesForOAuth20 returns the required OAuth2 scopes for the given operation.
//
// This is useful for token exchange scenarios where you need to know which scopes
// to request when obtaining a token for a downstream API call.
//
// Example:
//
//	requiredScopes := GetOAuth2ScopesForOAuth20(AddPetOperation)
//	token := exchangeTokenWithScopes(requiredScopes, "https://api.example.com")
//
// Returns nil if the operation has no scope requirements or if the operation is unknown.
func GetOAuth2ScopesForOAuth20(operation string) []string {
	scopes, ok := oauth2ScopesOAuth20[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(scopes))
	copy(result, scopes)
	return result
}

func (s *Client) securityOAuth20(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OAuth20(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"OAuth20\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
