apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: cortex-api-

labels:
  - pairs:
      app.kubernetes.io/name: cortex-api
      variant: utilities

resources:
  - ../../../../utilities/chrome-devtools-protocol-server
  - peer_authentication.yaml
  - sidecar.yaml
  - telemetry.yaml
