apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:b008a886fcacf59325915147809939ea596f6e6d6e15419c52be97139c9238be
  name: ghcr.io/hippocampus-dev/hippocampus/github-token-server
  newName: ghcr.io/hippocampus-dev/hippocampus/github-token-server
