apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:20038ceacfe0d1a93bb9e7910882e81a5e5a49fbe8adc04229de5d991225dc59
  name: ghcr.io/hippocampus-dev/hippocampus/github-token-server
  newName: ghcr.io/hippocampus-dev/hippocampus/github-token-server
