apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:fdf1348dd97305d6b954347a2d9638d3fbe75c98f7e8d1cdd3bd93c62ce1a5e5
  name: ghcr.io/hippocampus-dev/hippocampus/github-token-server
  newName: ghcr.io/hippocampus-dev/hippocampus/github-token-server
