apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cortex-api

resources:
- ../../base
- authorization_policy.yaml
- destination_rule.yaml
- envoy_filter.yaml
- gateway.yaml
- namespace.yaml
- network_policy.yaml
- peer_authentication.yaml
- request_authentication.yaml
- service_entry.yaml
- sidecar.yaml
- telemetry.yaml
- virtual_service.yaml
- waypoint.yaml
- redis

patches:
- path: patches/deployment.yaml
- path: patches/horizontal_pod_autoscaler.yaml
- path: patches/pod_disruption_budget.yaml
- path: patches/service.yaml

generators:
- secrets_from_vault.yaml
images:
- digest: sha256:730aebae1cb351876ad99f7309738cc75912fec88c4edcfe4defb2cb070df5f9
  name: ghcr.io/hippocampus-dev/hippocampus/chrome-devtools-protocol-server
  newName: ghcr.io/hippocampus-dev/hippocampus/chrome-devtools-protocol-server
- digest: sha256:728afdd144953c63de2da5a076cb0841e085db259a81980a77b5ad8b8c55fb55
  name: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
  newName: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
- digest: sha256:6739f2fdd290dfd7c192388f01aef1d8c5d7708b5c502072145ec16fda1c6d07
  name: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
