apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cortex-api

resources:
- ../../base
- authorization_policy.yaml
- destination_rule.yaml
- envoy_filter.yaml
- gateway.yaml
- namespace.yaml
- network_policy.yaml
- peer_authentication.yaml
- request_authentication.yaml
- service_entry.yaml
- sidecar.yaml
- telemetry.yaml
- virtual_service.yaml
- waypoint.yaml
- redis
- varnish
- tls-intercept-proxy
- ext-proc-proxy
- chrome-devtools-protocol-server

patches:
- path: patches/deployment.yaml
- path: patches/horizontal_pod_autoscaler.yaml
- path: patches/pod_disruption_budget.yaml
- path: patches/service.yaml

generators:
- secrets_from_vault.yaml
images:
- digest: sha256:d16ec56c8ab1dca16a0e041cd0c4f67c9b8041ae6e991390130974b160f8d4cd
  name: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
  newName: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
- digest: sha256:1288bc1402ff434da6e98820b895becbcb9d8d8837fb095f339ef6150e219911
  name: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/redis-proxy
