apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml

images:
- digest: sha256:a32d9614f26a637c0860d92a9f48464a53e5dc1ffc00e1d2c5380bf4ca54d9a5
  name: ghcr.io/hippocampus-dev/hippocampus/endpoint-broadcaster
  newName: ghcr.io/hippocampus-dev/hippocampus/endpoint-broadcaster
