apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml

images:
- digest: sha256:293030b5ad41c8a0887c4cdf7f53ace2fed9c14e08c70ba14d934b79b409d612
  name: ghcr.io/hippocampus-dev/hippocampus/endpoint-broadcaster
  newName: ghcr.io/hippocampus-dev/hippocampus/endpoint-broadcaster
