apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml

images:
- digest: sha256:eb4125d14ad026885a3694b512e6774f38832072444afa76da00fd25ad05a288
  name: ghcr.io/hippocampus-dev/hippocampus/endpoint-broadcaster
  newName: ghcr.io/hippocampus-dev/hippocampus/endpoint-broadcaster
