apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:a1d5bb4850479ee41be231717cb8b660b9426933be5247c8d8773b49878610dd
  name: ghcr.io/hippocampus-dev/hippocampus/persistentvolumeclaim-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/persistentvolumeclaim-hook
