apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:62b84ebf168dcf8cf28248fa8a104c5780f80fa1711e1d9076bbbab0142b0663
  name: ghcr.io/hippocampus-dev/hippocampus/persistentvolumeclaim-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/persistentvolumeclaim-hook
