apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:0263120e3bd52e7407afdd3c0e4d0b2d8985e89aaeda33aba6d6aa5a848798df
  name: ghcr.io/hippocampus-dev/hippocampus/kube-crud
  newName: ghcr.io/hippocampus-dev/hippocampus/kube-crud
