apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:e2cf4c5363c41c5ee971f2b98369524f9bc3f50ba62b433231b7c44dcbfc1e2e
  name: ghcr.io/hippocampus-dev/hippocampus/kube-crud
  newName: ghcr.io/hippocampus-dev/hippocampus/kube-crud
