apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: resource-field-hook
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: resource-field-hook
      app.kubernetes.io/component: ""
