apiVersion: v1
kind: Service
metadata:
  name: resource-field-hook
spec:
  selector:
    app.kubernetes.io/name: resource-field-hook
    app.kubernetes.io/component: ""
  ports:
    - name: https
      port: 9443
      protocol: TCP
      targetPort: https
