apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: embedding-retrieval

resources:
- ../../base
- gateway.yaml
- namespace.yaml
- network_policy.yaml
- peer_authentication.yaml
- service_entry.yaml
- sidecar.yaml
- telemetry.yaml
- virtual_service.yaml
- qdrant

patches:
- path: patches/deployment.yaml
- path: patches/horizontal_pod_autoscaler.yaml
- path: patches/pod_disruption_budget.yaml
- path: patches/service.yaml

generators:
- secrets_from_vault.yaml
images:
- digest: sha256:728afdd144953c63de2da5a076cb0841e085db259a81980a77b5ad8b8c55fb55
  name: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
  newName: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
- digest: sha256:db3cfd543a0c5f44d5a5a3c2b8a02572a8ed6b40cf10140d37370459616df054
  name: ghcr.io/hippocampus-dev/hippocampus/tcp-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/tcp-proxy
