apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: embedding-retrieval

resources:
- ../../base
- gateway.yaml
- namespace.yaml
- network_policy.yaml
- peer_authentication.yaml
- service_entry.yaml
- sidecar.yaml
- telemetry.yaml
- virtual_service.yaml
- qdrant

patches:
- path: patches/deployment.yaml
- path: patches/horizontal_pod_autoscaler.yaml
- path: patches/pod_disruption_budget.yaml
- path: patches/service.yaml

generators:
- secrets_from_vault.yaml
images:
- digest: sha256:1d1b4e7eff9c945cd9304af61bbd3c29ee1da91105c48b9ee1619ecc72edb901
  name: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
  newName: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
- digest: sha256:0c18d5a241a67b8e472631e376a296c9ad4effb0ca570473d2fa21a378ab60be
  name: ghcr.io/hippocampus-dev/hippocampus/tcp-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/tcp-proxy
