apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: embedding-retrieval

resources:
- ../../base
- gateway.yaml
- namespace.yaml
- network_policy.yaml
- peer_authentication.yaml
- service_entry.yaml
- sidecar.yaml
- telemetry.yaml
- virtual_service.yaml
- qdrant

patches:
- path: patches/deployment.yaml
- path: patches/horizontal_pod_autoscaler.yaml
- path: patches/pod_disruption_budget.yaml
- path: patches/service.yaml

generators:
- secrets_from_vault.yaml
images:
- digest: sha256:c860211ef2817949f679be5dbcf3a51603dcb319f8167596c2ebc4cfd702c11d
  name: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
  newName: ghcr.io/hippocampus-dev/hippocampus/exporter-merger
- digest: sha256:04b17a739556f469eb4f374abb4aae256b4c96d5867809e6f001946b1e92ca78
  name: ghcr.io/hippocampus-dev/hippocampus/tcp-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/tcp-proxy
