apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- digest: sha256:2bd36fafa15a90ab70bb61b9a6b67f930f79fdb3fbfcf1bfe657640bff6e4d2e
  name: ghcr.io/hippocampus-dev/hippocampus/lighthouse-exporter
  newName: ghcr.io/hippocampus-dev/hippocampus/lighthouse-exporter
