apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:af0cc5fec6509c71ea0cdbd0398a3667c808f56644f874f06247aec99f215ee3
  name: ghcr.io/hippocampus-dev/hippocampus/job-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/job-hook
