apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:7cd2c5324697634330a50ba14623e83cb7c67ad57cec11351bf84002f0bd4b69
  name: ghcr.io/hippocampus-dev/hippocampus/job-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/job-hook
