apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:d17b291540844419ed9dc90095f2955eed2d3719e4e664f566c02d0662299701
  name: ghcr.io/hippocampus-dev/hippocampus/spotify-mcp-server
  newName: ghcr.io/hippocampus-dev/hippocampus/spotify-mcp-server
