apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:56eebb0e98e25b43735f5381d7231621850435c1bc5229e406a1fcd74362195b
  name: ghcr.io/hippocampus-dev/hippocampus/spotify-mcp-server
  newName: ghcr.io/hippocampus-dev/hippocampus/spotify-mcp-server
