apiVersion: v1
kind: Service
metadata:
  name: spotify-mcp-server
spec:
  selector:
    app.kubernetes.io/name: spotify-mcp-server
    app.kubernetes.io/component: ""
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
