apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app.kubernetes.io/name: my-app
      app.kubernetes.io/component: ""
  template:
    metadata:
      labels:
        <<: *labels
      annotations:
        resource-field-hook.kaidotio.github.io/my-container.GOMEMLIMIT: '{{ scale .Value 0.9 }}'
    spec:
      containers:
        - name: my-container
          image: ghcr.io/hippocampus-dev/hippocampus/my-app
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-small-app
spec:
  replicas: 1
  selector:
    matchLabels: &small-labels
      app.kubernetes.io/name: my-small-app
      app.kubernetes.io/component: ""
  template:
    metadata:
      labels:
        <<: *small-labels
      annotations:
        resource-field-hook.kaidotio.github.io/my-container.GOMEMLIMIT: '{{ sub .Value (quantity "4Mi") }}'
    spec:
      containers:
        - name: my-container
          image: ghcr.io/hippocampus-dev/hippocampus/my-small-app
          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          resources:
            requests:
              cpu: 10m
              memory: 8Mi
            limits:
              cpu: 1000m
              memory: 16Mi
