apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pod_disruption_budget.yaml

images:
- digest: sha256:99c468cc5343b1670b5bff797bf210cd6e7e2720f2973f91872a62ea32a87de5
  name: ghcr.io/hippocampus-dev/hippocampus/translator
  newName: ghcr.io/hippocampus-dev/hippocampus/translator
