apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pod_disruption_budget.yaml

images:
- digest: sha256:f0517cdc4aa66dc43165c39b1841e74c9316cb4006ec46c4a837a3908d5d0e1e
  name: ghcr.io/hippocampus-dev/hippocampus/translator
  newName: ghcr.io/hippocampus-dev/hippocampus/translator
