apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-manifest-controller

resources:
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- role.yaml
- role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- crd

images:
- digest: sha256:1ea708af7a1376c44c94732d72948f74d3ff94821d76f567e3550842fe2d2e07
  name: ghcr.io/hippocampus-dev/hippocampus/grafana-manifest-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/grafana-manifest-controller
