apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../applications/slack-logger
- cron_job.yaml
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:1b82dfa024d7e0237d1b25cd600a539db48e35a89c46b7880c6b6ec297b30acb
  name: ghcr.io/hippocampus-dev/hippocampus/ephemeral-container
  newName: ghcr.io/hippocampus-dev/hippocampus/ephemeral-container
- digest: sha256:431008b15c54e75e1f579366ab2eb7586bdf73deb751655e9bf0e8b72fba6827
  name: ghcr.io/hippocampus-dev/hippocampus/slack-logger
  newName: ghcr.io/hippocampus-dev/hippocampus/slack-logger
