apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../applications/slack-logger
- cron_job.yaml
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:c32406815e78a1ec06e055c8cb6b56dac4a2b9ab6415de621e1a7452e3326812
- digest: sha256:ed934739ab79399bbcfd85b6e507e71afb6c163f6eaac38ec3c75ff004953432
  name: ghcr.io/hippocampus-dev/hippocampus/ephemeral-container
  newName: ghcr.io/hippocampus-dev/hippocampus/ephemeral-container
- digest: sha256:13c346a5bbf9e802572d81bf5a0064cf64a22c335b6c496b2f3be653d3f76358
  name: ghcr.io/hippocampus-dev/hippocampus/slack-logger
  newName: ghcr.io/hippocampus-dev/hippocampus/slack-logger
