# syntax=docker/dockerfile:1.4

FROM us-docker.pkg.dev/gemini-code-dev/gemini-cli/sandbox:latest
LABEL org.opencontainers.image.source="https://github.com/hippocampus-dev/hippocampus"

COPY bin/armyknife /usr/local/bin/armyknife
