apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml

images:
- digest: sha256:f58815af6a86cdef1d64725a84c1ced37f656deee0fb21b5fd1e448cba8db332
  name: ghcr.io/hippocampus-dev/hippocampus/github-actions-exporter-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/github-actions-exporter-controller
