#!/usr/bin/env bash

# https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_plugins/
if [ $# -eq 1 ]; then
  json=$(cat $1 | ruby -r yaml -r json -e 'puts JSON.generate(YAML.load(STDIN.read))')
  name=$(echo $json | jq -r '.metadata.name')
  behavior=$(echo $json | jq -r '.spec.behavior')
  keys=($(echo $json | jq -r '.spec.vaultSecrets[].key'))
# https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_krm_functions/
else
  json=$(cat - | ruby -r yaml -r json -e 'puts JSON.generate(YAML.load(STDIN.read))')
  name=$(echo $json | jq -r '.functionConfig.metadata.name')
  behavior=$(echo $json | jq -r '.functionConfig.spec.behavior')
  keys=($(echo $json | jq -r '.functionConfig.spec.vaultSecrets[].key'))
fi

if [ "$behavior" == "merge" ]; then
  exit 0
fi

cat <<EOS
kind: ResourceList
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: $name
    data:
$(for key in "${keys[@]}"; do echo "      $key: $(echo -n "dummy" | base64 -w0)"; done)
EOS
