apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml

images:
- digest: sha256:567891ff1d742b762b659b9bcd2f4e614b2a68ad29fbe4493b30df2df6359571
  name: ghcr.io/hippocampus-dev/hippocampus/snapshot-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/snapshot-controller
