apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml

images:
- digest: sha256:82ea1f0a129be9e79808788e92ad74b4324fcaa549389572c18606859ca2e1bd
  name: ghcr.io/hippocampus-dev/hippocampus/snapshot-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/snapshot-controller
