apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml

images:
- digest: sha256:8f03c9473948af0a8cbc2865ebcaec5529e5f907d6b31049ce648ef54ef1766e
  name: ghcr.io/hippocampus-dev/hippocampus/snapshot-controller
  newName: ghcr.io/hippocampus-dev/hippocampus/snapshot-controller
