apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fuse-csi-driver
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: fuse-csi-driver
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 200Mi
        - name: csi-node-driver-registrar
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 200Mi
