apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cron_job.yaml
images:
- digest: sha256:f0394b3a5f2eaefbd51a926468996ba1753c7cc883952daa3c1c379703cbe31d
  name: ghcr.io/hippocampus-dev/hippocampus/promphet
  newName: ghcr.io/hippocampus-dev/hippocampus/promphet
