apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cron_job.yaml
images:
- digest: sha256:2e7b7dc74b9bce641ed2a06f8a8a48c1d167df055291257c8fc1015b0bb11501
  name: ghcr.io/hippocampus-dev/hippocampus/promphet
  newName: ghcr.io/hippocampus-dev/hippocampus/promphet
