apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promphet

resources:
  - ../../base
  - namespace.yaml
  - network_policy.yaml
  - peer_authentication.yaml
  - sidecar.yaml
  - telemetry.yaml

patches:
  - path: patches/cron_job.yaml

configMapGenerator:
  - name: promphet
    files:
      - config.yaml=files/jobs.yaml
