package v1

import (
	v1 "k8s.io/api/core/v1"
	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RunnerSpec defines the desired state of Runner
// Scope is inferred from repo field: if repo is set, scope is repository; otherwise, scope is organization.
// +kubebuilder:validation:XValidation:rule="!(has(self.repo) && has(self.runnerGroup))",message="runnerGroup is organization-level only and cannot be set together with repo"
type RunnerSpec struct {
	// Image using by self-hosted runner
	Image string `json:"image"`
	// Owner specifies the GitHub organization or user
	// +kubebuilder:validation:Pattern=`^[^/]+$`
	Owner string `json:"owner"`
	// Repo specifies the GitHub repository name. If set, runner is registered at repository level.
	// If not set, runner is registered at organization level.
	// +kubebuilder:validation:Pattern=`^[^/]+$`
	// +optional
	Repo string `json:"repo,omitempty"`
	// RunnerGroup specifies the GitHub runner group the runner joins. Runner groups exist at the organization level, so config.sh resolves any name but the repository's own default to nothing once repo is set.
	// Leaving it unset takes the group GitHub reports as the default, which every repository the runner's organization holds can reach.
	// A name may contain no whitespace, since the runner binary passes it to config.sh as one argument.
	// +kubebuilder:validation:Pattern=`^\S+$`
	// +optional
	RunnerGroup string `json:"runnerGroup,omitempty"`
	// Labels specifies additional targets for runs-on. self-hosted and github-actions-runner-controller are always registered as ones.
	// A label may contain neither whitespace nor a comma, since the runner binary passes them to config.sh as one comma-separated argument.
	// +kubebuilder:validation:items:Pattern=`^[^\s,]+$`
	// +optional
	Labels []string `json:"labels,omitempty"`
	// Disableupdate passes --disableupdate to config.sh, which keeps the runner on the version its image carries instead of letting it update itself.
	// +optional
	Disableupdate bool `json:"disableupdate,omitempty"`
	// Selects a key of a GitHub Token secret in the runner's namespace
	TokenSecretKeyRef *v1.SecretKeySelector `json:"tokenSecretKeyRef,omitempty"`
	AppSecretRef      *v1.SecretEnvSource   `json:"appSecretRef,omitempty"`
	// +optional
	Template Template `json:"template,omitzero"`
	// +optional
	BuilderContainerSpec BuilderContainerSpec `json:"builderContainerSpec,omitzero"`
	// +optional
	RunnerContainerSpec RunnerContainerSpec `json:"runnerContainerSpec,omitzero"`
}

// Template defines the pod template generated by runner
type Template struct {
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
	// +kubebuilder:pruning:PreserveUnknownFields
	metaV1.ObjectMeta `json:"metadata,omitempty"`
	// +optional
	Spec Spec `json:"spec,omitzero" protobuf:"bytes,2,opt,name=spec"`
}

// Spec defines the additional pod spec generated by runner
type Spec struct {
	// ServiceAccountName is the name of the ServiceAccount to use to run this pod.
	// More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
	// +optional
	ServiceAccountName string `json:"serviceAccountName,omitempty" protobuf:"bytes,8,opt,name=serviceAccountName"`
	// List of volumes that can be mounted by containers belonging to the pod.
	// More info: https://kubernetes.io/docs/concepts/storage/volumes
	// +patchMergeKey=name
	// +patchStrategy=merge,retainKeys
	Volumes []v1.Volume `json:"volumes,omitempty" patchStrategy:"merge,retainKeys" patchMergeKey:"name" protobuf:"bytes,1,rep,name=volumes"`
	// RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group, which should be used to run this pod.  If no RuntimeClass resource matches the named class, the pod will not be run.
	// If unset or empty, the "legacy" RuntimeClass will be used, which is an implicit class with an empty definition that uses the default runtime handler.
	// More info: https://git.k8s.io/enhancements/keps/sig-node/585-runtime-class
	// +optional
	RuntimeClassName *string `json:"runtimeClassName,omitempty" protobuf:"bytes,29,opt,name=runtimeClassName"`
}

// Additional Spec for builder container.
type BuilderContainerSpec struct {
	// List of sources to populate environment variables in the container.
	// The keys defined within a source must be a C_IDENTIFIER.
	// All invalid keys will be reported as an event when the container is starting.
	// When a key exists in multiple sources, the value associated with the last source will take precedence.
	// Values defined by an Env with a duplicate key will take precedence.
	// Cannot be updated.
	// +optional
	EnvFrom []v1.EnvFromSource `json:"envFrom,omitempty" protobuf:"bytes,19,rep,name=envFrom"`
	// List of environment variables to set in the runner container.
	// +patchMergeKey=name
	// +patchStrategy=merge
	Env []v1.EnvVar `json:"env,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,7,rep,name=env"`
	// Compute Resources required by this container.
	// More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
	// +optional
	Resources v1.ResourceRequirements `json:"resources,omitzero" protobuf:"bytes,8,opt,name=resources"`
	// Pod volumes to mount into the container's filesystem.
	// Cannot be updated.
	// +patchMergeKey=mountPath
	// +patchStrategy=merge
	VolumeMounts []v1.VolumeMount `json:"volumeMounts,omitempty" patchStrategy:"merge" patchMergeKey:"mountPath" protobuf:"bytes,9,rep,name=volumeMounts"`
}

// Additional Spec for runner container.
type RunnerContainerSpec struct {
	// Isolation selects what a container runtime started inside the runner is given.
	// privileged opens the whole capability bounding set and voids the seccomp profile, which a daemon needs.
	// userns adds only the capabilities a rootless one needs, unmasks /proc, and voids the seccomp profile as well since containerd's default carries no pivot_root, and the controller pins the pod's spec.hostUsers to false so those capabilities hold against the pod's own user namespace rather than the node.
	// userns also mounts an emptyDir named containers-storage over the rootless container storage and sets STORAGE_DRIVER to overlay on it, which counts against ephemeral-storage and leaves both names taken.
	// The runner process itself holds none of the capabilities either value adds, and reaches them through sudo.
	// +kubebuilder:validation:Enum=userns;privileged
	// +optional
	Isolation string `json:"isolation,omitempty"`
	// List of sources to populate environment variables in the container.
	// The keys defined within a source must be a C_IDENTIFIER.
	// All invalid keys will be reported as an event when the container is starting.
	// When a key exists in multiple sources, the value associated with the last source will take precedence.
	// Values defined by an Env with a duplicate key will take precedence.
	// Cannot be updated.
	// +optional
	EnvFrom []v1.EnvFromSource `json:"envFrom,omitempty" protobuf:"bytes,19,rep,name=envFrom"`
	// List of environment variables to set in the runner container.
	// +patchMergeKey=name
	// +patchStrategy=merge
	Env []v1.EnvVar `json:"env,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,7,rep,name=env"`
	// Compute Resources required by this container.
	// More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
	// +optional
	Resources v1.ResourceRequirements `json:"resources,omitzero" protobuf:"bytes,8,opt,name=resources"`
	// Pod volumes to mount into the container's filesystem.
	// Cannot be updated.
	// +patchMergeKey=mountPath
	// +patchStrategy=merge
	VolumeMounts []v1.VolumeMount `json:"volumeMounts,omitempty" patchStrategy:"merge" patchMergeKey:"mountPath" protobuf:"bytes,9,rep,name=volumeMounts"`
}

// RunnerStatus defines the observed state of Runner
type RunnerStatus struct{}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Runner is the schema for the runners API
type Runner struct {
	metaV1.TypeMeta   `json:",inline"`
	metaV1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RunnerSpec   `json:"spec,omitempty"`
	Status RunnerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RunnerList contains a list of Attack
type RunnerList struct {
	metaV1.TypeMeta `json:",inline"`
	metaV1.ListMeta `json:"metadata,omitempty"`
	Items           []Runner `json:"items"`
}
