apiVersion: skaffold.github-actions-runner.kaidotio.github.io/v1
kind: ScaleSet
metadata:
  name: scale-set-example
spec:
  image: ubuntu:24.04
  owner: kaidotio
  repo: hippocampus
  labels:
    - scaleset
  minRunners: 0
  maxRunners: 5
  tokenSecretKeyRef:
    name: credentials
    key: GITHUB_TOKEN
