apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:6de797eee96923615dbf3367640cd371b69e720c514e01313a241f81743456ac
  name: ghcr.io/hippocampus-dev/hippocampus/exactly-one-pod-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/exactly-one-pod-hook
