apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:c03dbe85d2c7729b06bf9b8d65ef464981cd3f2a24dcb9e78d47b129171fc41f
  name: ghcr.io/hippocampus-dev/hippocampus/exactly-one-pod-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/exactly-one-pod-hook
