apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- peer_authentication.yaml
- sidecar.yaml
- telemetry.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:0743efbad58537639dbf41d0e7a15c888fc02b51a5cee1225c806541edc0edd9
  name: ghcr.io/hippocampus-dev/hippocampus/cloudevents-alertmanager
  newName: ghcr.io/hippocampus-dev/hippocampus/cloudevents-alertmanager
