apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # issuer + 1
spec:
  dnsNames:
    - gateway-proxy.gateway-proxy.svc
    - gateway-proxy.gateway-proxy.svc.cluster.local
