apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dedicated_container_ingress.yaml

images:
- digest: sha256:15349077e682abb893835b86bcfbf88e847ca5789496615ca7b8ee1796b8b134
  name: ghcr.io/hippocampus-dev/hippocampus/remotty
  newName: ghcr.io/hippocampus-dev/hippocampus/remotty

configurations:
- kustomizeconfig.yaml
