apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:311dc284138fb2a0d94574fd92e6f4ae67552f7019e639bd0c7341471a13c9bc
  name: ghcr.io/hippocampus-dev/hippocampus/embedding-gateway
  newName: ghcr.io/hippocampus-dev/hippocampus/embedding-gateway
