apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:2defac407a6ed9cd5fb6e0c804aa97cf9a3c2253fc564deae9f1588c07d53885
  name: ghcr.io/hippocampus-dev/hippocampus/embedding-gateway
  newName: ghcr.io/hippocampus-dev/hippocampus/embedding-gateway
