apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:5fd4c5e76565651ea516ff6f527a33cc21e818c1ec374cfa6d5b8cb2a8673114
  name: ghcr.io/hippocampus-dev/hippocampus/csviewer
  newName: ghcr.io/hippocampus-dev/hippocampus/csviewer
