apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- gateway_class.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
- validating_webhook_configuration.yaml
images:
- digest: sha256:0701278555c182147c2691b5bf85abeec493b083703b4cac1c0be32c793cdb5b
  name: ghcr.io/hippocampus-dev/hippocampus/gateway-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/gateway-proxy
