apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- gateway_class.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
- validating_webhook_configuration.yaml
images:
- digest: sha256:c7603622e4f9ad7a4fbf22b57365b25cb819e5143a3aef4569bfc275243057c8
  name: ghcr.io/hippocampus-dev/hippocampus/gateway-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/gateway-proxy
