apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- cluster_role.yaml
- gateway_class.yaml
- cluster_role_binding.yaml
- deployment.yaml
- issuer.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
- validating_webhook_configuration.yaml
images:
- digest: sha256:bd6b8f24e16ea12cfc752150c9d9a4a9304fbba90901ec4d84df63612b332ba3
  name: ghcr.io/hippocampus-dev/hippocampus/gateway-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/gateway-proxy
