apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-proxy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-proxy
      app.kubernetes.io/component: ""
