apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-proxy
subjects:
  - kind: ServiceAccount
    name: gateway-proxy
