apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-proxy
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - gateway-proxy
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
