apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:ab90d1945d250aa2277db7ae18491043725fab76606d9219810807dccd42f9a3
  name: ghcr.io/hippocampus-dev/hippocampus/oauth-bridge
  newName: ghcr.io/hippocampus-dev/hippocampus/oauth-bridge
