apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:775fc06dcd0bcafcac7d1c7236c9d5aebf9add32bb5f72eebfa10770eb6ac392
  name: ghcr.io/hippocampus-dev/hippocampus/oauth-bridge
  newName: ghcr.io/hippocampus-dev/hippocampus/oauth-bridge
