apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- broker.yaml
- service.yaml
- trigger.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:7ae408b5d51a8df2921186f99aa9ce3c9f5529abebd4e8f95189e095d600ada4
  name: ghcr.io/hippocampus-dev/hippocampus/cloudevents-logger
  newName: ghcr.io/hippocampus-dev/hippocampus/cloudevents-logger
