apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- runner.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:4d0371c76accb3d3837f472a081b8e1eb64c2249c494faa327cd43464f425cca
  name: ghcr.io/hippocampus-dev/hippocampus/runner
  newName: ghcr.io/hippocampus-dev/hippocampus/runner
