apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- runner.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:369afbd3e0eca96593c0882757d9c00ded55c98f4a6ca6c7851b27e22a68b0fd
  name: ghcr.io/hippocampus-dev/hippocampus/runner
  newName: ghcr.io/hippocampus-dev/hippocampus/runner
