apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- peer_authentication.yaml
- sidecar.yaml
- telemetry.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:a3ca1095097be15f19384adf2afa2df28c070c0baf24377582b6e3906fd0522c
  name: ghcr.io/hippocampus-dev/hippocampus/loganomaly
  newName: ghcr.io/hippocampus-dev/hippocampus/loganomaly
