apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetragon-operator
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app.kubernetes.io/name: tetragon
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      serviceAccountName: tetragon-operator
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tetragon-operator
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsUser: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: quay.io/cilium/tetragon-operator
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/tetragon-operator
          args:
            - serve
            - --config-dir=/etc/tetragon/operator.conf.d/
            - --metrics-bind-address=:2113
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: /etc/tetragon/operator.conf.d/
              name: tetragon-operator-config
              readOnly: true
      volumes:
        - name: tetragon-operator-config
          configMap:
            name: tetragon-operator-config
