apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml

images:
- digest: sha256:7f1c1996c19a51c6e46592a86de6b2af2d091f1c6ae5de5b28d9602205d006e6
  name: ghcr.io/hippocampus-dev/hippocampus/whisper-worker
  newName: ghcr.io/hippocampus-dev/hippocampus/whisper-worker
