apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml

images:
- digest: sha256:5bcd6cca81489584ed54e0086e89dcfe3e1c9835af921529676ba8455395a6ca
  name: ghcr.io/hippocampus-dev/hippocampus/whisper-worker
  newName: ghcr.io/hippocampus-dev/hippocampus/whisper-worker
