apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:a2dc63dd07bd09cd2fb1bfb532f226bc5268ceeaa66ae53fc8c26a9e295dda29
  name: ghcr.io/hippocampus-dev/hippocampus/reporting-server
  newName: ghcr.io/hippocampus-dev/hippocampus/reporting-server
