apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:2e56a6ed6228326faa1c15050f02f8e97783f9a8d24f3a4e4a3ba456c29bf4cc
  name: ghcr.io/hippocampus-dev/hippocampus/reporting-server
  newName: ghcr.io/hippocampus-dev/hippocampus/reporting-server
