apiVersion: v1
kind: Namespace
metadata:
  name: hippocampus-dev-slack-oauth-bridge
  labels:
    name: hippocampus-dev-slack-oauth-bridge
    # waypoint requires baseline pod security
    pod-security.kubernetes.io/enforce: baseline
