[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/stdout
logfile_maxbytes=0

[program:ttyd]
command=ttyd --port 7681 --writable tmux new-session -A -s main
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

[program:chisel]
command=chisel server --port 8080 --reverse --auth %(ENV_CHISEL_AUTH)s
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

[unix_http_server]
file=/tmp/supervisor.sock
