apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:397b7273ee003ae96fd7543e321826c69471fd714ee688d06df4cbe5c5908498
  name: ghcr.io/hippocampus-dev/hippocampus/talk
  newName: ghcr.io/hippocampus-dev/hippocampus/talk
