apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:a2123069ed0bd3bdbcd7e0acad561b1608b4d77308cf9f536d6ad8eb10ede605
  name: ghcr.io/hippocampus-dev/hippocampus/talk
  newName: ghcr.io/hippocampus-dev/hippocampus/talk
