apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:4c73db28462c12a761ee6d8549e83694eea142469c7803bad799c2117eec66c1
  name: ghcr.io/hippocampus-dev/hippocampus/prometheus-metrics-proxy-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/prometheus-metrics-proxy-hook
