apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- issuer.yaml
- mutating_webhook_configuration.yaml
- pod_disruption_budget.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:8d38b300deb906d2b06fa737429f22699174a905c5c0b13c0811c728e93fe407
  name: ghcr.io/hippocampus-dev/hippocampus/prometheus-metrics-proxy-hook
  newName: ghcr.io/hippocampus-dev/hippocampus/prometheus-metrics-proxy-hook
