apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: e2e-listenerset
spec:
  parentRef:
    name: skaffold-e2e-gateway
  listeners:
    - name: tcp-9000
      port: 9000
      protocol: TCP
