apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-local-dns
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        policy.cilium.io/no-track-port: "53"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
        prometheus.io/port: "9253"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: node-local-dns
          resources:
            requests:
              cpu: 100m
              memory: 70Mi
            limits:
              cpu: 1000m
              memory: 256Mi
