apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:0d122f0d713fcc4ca74946dc80ca8e322a25c3d7b1415cabc18cfa39d982a822
  name: ghcr.io/hippocampus-dev/hippocampus/bakery
  newName: ghcr.io/hippocampus-dev/hippocampus/bakery
