apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:ee4cf2efe9fc0cd3ea34df26df7fde9f82ce592206624566c52ec54cb711cf0a
  name: ghcr.io/hippocampus-dev/hippocampus/bakery
  newName: ghcr.io/hippocampus-dev/hippocampus/bakery
