apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:0cba8bec4751374aaf9d2ff5ffd1409257ce797bc8d94499dea386956758a3d6
  name: ghcr.io/hippocampus-dev/hippocampus/bakery
  newName: ghcr.io/hippocampus-dev/hippocampus/bakery
