apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemon_set.yaml
images:
- digest: sha256:f185f0e7a7ae2b63833c57b6c591983c2b0d6bbfdcbd98d4a197a1d0e8552cbc
  name: ghcr.io/hippocampus-dev/hippocampus/connectracer
  newName: ghcr.io/hippocampus-dev/hippocampus/connectracer
