apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemon_set.yaml
images:
- digest: sha256:aa85c9b44f2363b80228ab60c03ae19d5faa608c8fff76623d517451598ee371
  name: ghcr.io/hippocampus-dev/hippocampus/connectracer
  newName: ghcr.io/hippocampus-dev/hippocampus/connectracer
