apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hippocampus-dev-device-flow-bridge

resources:
  - namespace.yaml
  - network_policy.yaml
  - waypoint.yaml
  - device-flow-bridge
  - redis
