apiVersion: v1
kind: Namespace
metadata:
  name: hippocampus-dev-device-flow-bridge
  labels:
    name: device-flow-bridge
    # waypoint requires baseline pod security
    pod-security.kubernetes.io/enforce: baseline
