apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pod_disruption_budget.yaml
images:
- digest: sha256:926623e113b248c5027e1936269af03cc293790bf84604596fda7a64e684f180
  name: ghcr.io/hippocampus-dev/hippocampus/slack-bolt-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/slack-bolt-proxy
