apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: fluentd-aggregator
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: tcp-gateway
    namespace: gateway-proxy
  listeners:
    - name: tcp-24224
      port: 24224
      protocol: TCP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              name: fluentd
