apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:25c8c11cc7a4da3de8bfaa369f198b3a15071f2e8bb71644d087159744c2db74
  name: ghcr.io/hippocampus-dev/hippocampus/token-request-server
  newName: ghcr.io/hippocampus-dev/hippocampus/token-request-server
