apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
images:
- digest: sha256:6b44ec5b77c2268fff002763ce6615cd94d7572f638fe73db9eb93c0cb3d97f9
  name: ghcr.io/hippocampus-dev/hippocampus/token-request-server
  newName: ghcr.io/hippocampus-dev/hippocampus/token-request-server
