apiVersion: v1
kind: Service
metadata:
  name: seata
spec:
  selector:
    app.kubernetes.io/name: seata
    app.kubernetes.io/component: ""
  ports:
    - name: tcp
      port: 8091
      protocol: TCP
      targetPort: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: seata-raft
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app.kubernetes.io/name: seata
    app.kubernetes.io/component: ""
  ports:
    - name: tcp
      port: 8091
      protocol: TCP
      targetPort: tcp
    - name: tcp-raft
      port: 9091
      protocol: TCP
      targetPort: raft
