apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- digest: sha256:c00644da5e686aa96bf1267058eb8d0a2fc7c63feae68b390c41a87544ab18ee
  name: ghcr.io/hippocampus-dev/hippocampus/realtime-search-exporter
  newName: ghcr.io/hippocampus-dev/hippocampus/realtime-search-exporter
