apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- digest: sha256:c91575d6da4c7b0597a75bb849d88a2cafadb96363f582fd3cff03e1e24a9d91
  name: ghcr.io/hippocampus-dev/hippocampus/realtime-search-exporter
  newName: ghcr.io/hippocampus-dev/hippocampus/realtime-search-exporter
