apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:013f8ecac07952f9204dd6c4911d4dfa9077d4ea31eef47ebef02b1338b65af3
  name: ghcr.io/hippocampus-dev/hippocampus/libsodium-encryptor
  newName: ghcr.io/hippocampus-dev/hippocampus/libsodium-encryptor
