apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:58f1cef25ca20f23f5b1fa98eb748a9bc2bc7e6df78a4a953bc24ef7aa7250ba
  name: ghcr.io/hippocampus-dev/hippocampus/libsodium-encryptor
  newName: ghcr.io/hippocampus-dev/hippocampus/libsodium-encryptor
