apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:ce5b211807938ebaa9add342b564efd0a52644c6bdad45a16f1f28e94f0a9aca
  name: ghcr.io/hippocampus-dev/hippocampus/libsodium-encryptor
  newName: ghcr.io/hippocampus-dev/hippocampus/libsodium-encryptor
