apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:91285058fdf16f30e9dccea996692607a600862263fe2c3dc56b9ad89880a469
  name: ghcr.io/hippocampus-dev/hippocampus/http-redis-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/http-redis-proxy
