apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- horizontal_pod_autoscaler.yaml
- pod_disruption_budget.yaml
- service.yaml
images:
- digest: sha256:8b30d9122099aeb8afc10da08b7e70bd9f6a2b4921cb6b6c97e1cda1fae8709f
  name: ghcr.io/hippocampus-dev/hippocampus/http-redis-proxy
  newName: ghcr.io/hippocampus-dev/hippocampus/http-redis-proxy
