apiVersion: v1
kind: Namespace
metadata:
  name: runner
  labels:
    name: runner
    # runner uses Kaniko for container image building, and privileged-scale-set runs a container runtime
    pod-security.kubernetes.io/enforce: privileged
