apiVersion: kustomize.kaidotio.github.io/v1
kind: SecretsFromVault
metadata:
  name: hippocampus-dev-spotify-oauth-bridge
spec:
  vaultSecrets:
    - path: /kv/data/hippocampus-dev-spotify-oauth-bridge
      key: CLIENT_SECRET
