// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type EncryptedMessage struct {
	ID            uint32         `json:"id"`
	ChannelName   string         `json:"channel_name"`
	MessageTs     string         `json:"message_ts"`
	ThreadTs      sql.NullString `json:"thread_ts"`
	Salt          []byte         `json:"salt"`
	EncryptedData []byte         `json:"encrypted_data"`
	Timestamp     time.Time      `json:"timestamp"`
	CreatedAt     time.Time      `json:"created_at"`
}
