name: ghelpers
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/00_ghadapter.yaml"
      - ".github/ghelpers/ghadapter/**"
      - "!**/*.md"
  workflow_dispatch:
    inputs: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  packages: write
  pull-requests: write
  id-token: write
jobs:
  runner:
    if: github.repository_owner == 'kaidotio'
    uses: ./.github/workflows/reusable_dynamic-runner.yaml
    with:
      labels: self-hosted,local
      fallback-runner: ubuntu-24.04
    secrets: inherit
  publish:
    needs: runner
    if: ${{ !cancelled() && needs.runner.outputs.runner }}
    timeout-minutes: 10
    runs-on: ${{ fromJSON(needs.runner.outputs.runner) }}
    env:
      IMAGE: ghelpers
      KUSTOMIZATION: ""
    steps:
      - if: contains(needs.runner.outputs.runner, 'local')
        run: echo "GIT_CONFIG_GLOBAL=${{ runner.temp }}/gitconfig" >> $GITHUB_ENV
      - run: git config --global submodule.recurse false
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github/
      - uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/.cache/docker-build/ghelpers
          key: ${{ runner.os }}-ghadapter-docker-${{ hashFiles('.github/ghelpers/ghadapter/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-ghadapter-docker-
      - if: contains(needs.runner.outputs.runner, 'local')
        run: echo "DOCKER_CONFIG=${{ runner.temp }}/.docker" >> $GITHUB_ENV
      - uses: ./.github/actions/setup-docker
      - run: |
          set -eo pipefail
          IMAGE_PATH="${GITHUB_REPOSITORY}/${IMAGE}"
          GHCR_IMAGE="ghcr.io/${IMAGE_PATH}"
          TAG="${GITHUB_REF##*/}"
          opt=""
          if [ -d "${{ runner.temp }}/.cache/docker-build/ghelpers" ]; then
            opt="--cache-from type=local,src=${{ runner.temp }}/.cache/docker-build/ghelpers"
          else
            opt="--cache-from type=registry,ref=${GHCR_IMAGE}:cache"
          fi
          (
            cd .github/ghelpers/ghadapter

            docker buildx build --output "type=docker,name=${GHCR_IMAGE}/ghadapter:${TAG},push=false" ${opt} --cache-to "type=local,mode=max,dest=${{ runner.temp }}/.cache/docker-build/ghelpers" --cache-to "type=registry,ref=${GHCR_IMAGE}:cache,mode=max" .
            docker push "${GHCR_IMAGE}/ghadapter:${TAG}"
          )
        env:
          GITHUB_TOKEN: ${{ github.token }}
  scan:
    if: ${{ !cancelled() && github.repository_owner == 'kaidotio' && needs.publish.result == 'success' }}
    needs: [runner, publish]
    uses: ./.github/workflows/reusable_scan-image.yaml
    with:
      image: ghcr.io/${{ github.repository }}/ghelpers/ghadapter:${{ github.ref_name }}
      runner: ${{ needs.runner.outputs.runner }}
    secrets: inherit
