name: Release/insight
on:
  release:
    types:
      - created
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  packages: read
  id-token: write
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  runner:
    if: github.repository_owner == 'kaidotio'
    uses: ./.github/workflows/reusable_dynamic-runner.yaml
    with:
      labels: self-hosted,local
      fallback-runner: ubuntu-24.04
    secrets: inherit
  release:
    needs: runner
    if: ${{ !cancelled() && needs.runner.outputs.runner }}
    timeout-minutes: 10
    runs-on: ${{ fromJSON(needs.runner.outputs.runner) }}
    steps:
      - if: contains(needs.runner.outputs.runner, 'local')
        run: echo "GIT_CONFIG_GLOBAL=${{ runner.temp }}/gitconfig" >> $GITHUB_ENV
      - run: git config --global submodule.recurse false
      - if: contains(needs.runner.outputs.runner, 'local')
        run: echo "DOCKER_CONFIG=${{ runner.temp }}/.docker" >> $GITHUB_ENV
      - run: docker login ghcr.io -u "${GITHUB_REPOSITORY_OWNER}" -p "${GITHUB_TOKEN}"
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            insight/
            packages/
      - uses: actions/cache@v5
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-insight-packages-${{ hashFiles('insight/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-insight-packages-
      - uses: actions/cache@v5
        with:
          path: insight/target
          key: ${{ runner.os }}-insight-${{ hashFiles('insight/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-insight-
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          set -eo pipefail
          mkdir -p ${{ runner.temp }}/bin
          curl -fsSL https://github.com/goreleaser/goreleaser/releases/download/v2.8.2/goreleaser_Linux_x86_64.tar.gz | tar zx --no-same-owner -C ${{ runner.temp }}/bin goreleaser
          curl -fsSL https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz | tar zx --no-same-owner -C ${{ runner.temp }}/bin cross
          echo "${{ runner.temp }}/bin" >> "$GITHUB_PATH"
      - run: |
          set -eo pipefail
          rustup component add rustfmt
          rustup component add rust-src
          goreleaser release
        working-directory: insight
