apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:931c0cfbd2edd6e45683ad18cc5ea92fa1d859d88ca8fbcc5ebac4dda3c76e0c
  name: ghcr.io/hippocampus-dev/hippocampus/cloudevents-relay
  newName: ghcr.io/hippocampus-dev/hippocampus/cloudevents-relay
