apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:acf4d417e08862952408008ec56a8f013a7c3a7e3d2d61985eba36783123ab3f
  name: ghcr.io/hippocampus-dev/hippocampus/cloudevents-relay
  newName: ghcr.io/hippocampus-dev/hippocampus/cloudevents-relay
