apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- peer_authentication.yaml
- sidecar.yaml
- telemetry.yaml

configurations:
- kustomizeconfig.yaml
images:
- digest: sha256:9b11ca98907e166c6d413b901ca8fcf6dcee6120092dc6341c85e879ca2d778d
  name: ghcr.io/hippocampus-dev/hippocampus/loganomaly
  newName: ghcr.io/hippocampus-dev/hippocampus/loganomaly
